# Generated by Django 5.2.17 on 2026-08-27 12:49

import apps.core.db.uuid7
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_tenant_fiscal_regime"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("partner_id", models.UUIDField()),
                ("contact", models.CharField(blank=True, max_length=150)),
                ("source_lead_id", models.UUIDField(blank=True, null=True)),
                ("date", models.DateField()),
                ("date_confirmed", models.DateField(blank=True, null=True)),
                ("commitment_date", models.DateField(blank=True, null=True)),
                ("pricelist_id", models.UUIDField(blank=True, null=True)),
                ("currency", models.CharField(default="MGA", max_length=3)),
                ("payment_term_id", models.UUIDField(blank=True, null=True)),
                (
                    "incoterm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW — A l'usine"),
                            ("FOB", "FOB — Franco a bord"),
                            ("CIF", "CIF — Cout, assurance et fret"),
                            ("DAP", "DAP — Rendu au lieu de destination"),
                            ("DDP", "DDP — Rendu droits acquittes"),
                        ],
                        max_length=8,
                    ),
                ),
                ("delivery_address", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyee"),
                            ("confirmed", "Confirmee"),
                            ("in_preparation", "En preparation"),
                            ("partially_delivered", "Livree partiellement"),
                            ("delivered", "Livree"),
                            ("invoiced", "Facturee"),
                            ("closed", "Cloturee"),
                            ("cancelled", "Annulee"),
                            ("blocked", "Bloquee"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("cancel_reason", models.TextField(blank=True)),
                ("blocked_reason", models.TextField(blank=True)),
                (
                    "amount_untaxed",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_tax",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_total_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="sales.salesquotation",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_order",
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("variant_id", models.UUIDField(blank=True, null=True)),
                ("is_custom", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=255)),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=1, max_digits=18),
                ),
                ("uom", models.CharField(blank=True, max_length=16)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("tax_id", models.UUIDField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "cost_estimate_mga",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "margin_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("stock", "Sur stock"),
                            ("production", "A produire"),
                            ("achat", "A acheter"),
                        ],
                        default="stock",
                        max_length=16,
                    ),
                ),
                (
                    "qty_delivered",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_invoiced",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_to_produce",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("mrp_order_id", models.UUIDField(blank=True, null=True)),
                ("purchase_order_line_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_order_line",
                "ordering": ["sequence"],
            },
        ),
    ]
