# Generated by Django 5.2.17 on 2026-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_salesorder_salesorderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="invoiced_amount_mga",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="billing_policy",
            field=models.CharField(
                choices=[
                    ("on_ordered_qty", "Sur quantite commandee"),
                    ("on_delivered_qty", "Sur quantite livree"),
                    ("on_deposit", "Sur acompte"),
                    ("on_production_progress", "A l'avancement de production"),
                ],
                default="on_ordered_qty",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="deposit_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
