# Generated by Django 5.2.17 on 2026-08-27 13:51

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_tenant_fiscal_regime"),
        ("sales", "0004_salesrecurrence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="is_export",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SalesCustomerCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.UUIDField()),
                ("label", models.CharField(max_length=150)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("closure", "Fermeture"),
                            ("peak_activity", "Pic d'activite"),
                            ("campaign", "Campagne"),
                            ("inventory", "Inventaire"),
                        ],
                        max_length=16,
                    ),
                ),
                ("impact_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_customer_calendar",
            },
        ),
        migrations.CreateModel(
            name="SalesTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("period", models.CharField(max_length=7)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("company", "Entreprise"),
                            ("team", "Equipe"),
                            ("salesperson", "Commercial"),
                        ],
                        default="company",
                        max_length=16,
                    ),
                ),
                ("scope_ref", models.UUIDField(blank=True, null=True)),
                (
                    "amount_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_target",
            },
        ),
        migrations.CreateModel(
            name="SalesForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("period", models.CharField(max_length=7)),
                ("variant_id", models.UUIDField()),
                ("partner_id", models.UUIDField(blank=True, null=True)),
                (
                    "qty_forecast",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_actual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                        ],
                        default="low",
                        max_length=8,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=64)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_forecast",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "period", "variant_id", "partner_id"),
                        name="uniq_sales_forecast_tenant_period_variant_partner",
                    )
                ],
            },
        ),
    ]
