# Generated by Django 5.2.17 on 2026-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_salesorder_is_export_salescustomercalendar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderline",
            name="stock_reservation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
