# Generated by Django 5.2.17 on 2026-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_salesorderline_stock_reservation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderline",
            name="tax_rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="salesquotationline",
            name="tax_rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
