# Generated by Django 5.2.17 on 2026-09-09 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_t5_tenant_mobile_payment_provider"),
        ("sales", "0007_salesorderline_tax_rate_salesquotationline_tax_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="external_reference",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="ingestion_anomaly",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shop_code",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_reference", ""), _negated=True),
                fields=("tenant", "shop_code", "external_reference"),
                name="uniq_sales_order_shop_reference",
            ),
        ),
    ]
