# Generated by Django 5.2.17 on 2026-09-11 15:17

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_t7_shop_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salescustomercalendar",
            name="type",
            field=models.CharField(
                choices=[
                    ("closure", "Fermeture"),
                    ("peak_activity", "Pic d'activité"),
                    ("campaign", "Campagne"),
                    ("inventory", "Inventaire"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="incoterm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW — À l'usine"),
                    ("FOB", "FOB — Franco à bord"),
                    ("CIF", "CIF — Coût, assurance et fret"),
                    ("DAP", "DAP — Rendu au lieu de destination"),
                    ("DDP", "DDP — Rendu droits acquittés"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyée"),
                    ("confirmed", "Confirmée"),
                    ("in_preparation", "En préparation"),
                    ("partially_delivered", "Livrée partiellement"),
                    ("delivered", "Livrée"),
                    ("invoiced", "Facturée"),
                    ("closed", "Clôturée"),
                    ("cancelled", "Annulée"),
                    ("blocked", "Bloquée"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="billing_policy",
            field=models.CharField(
                choices=[
                    ("on_ordered_qty", "Sur quantité commandée"),
                    ("on_delivered_qty", "Sur quantité livrée"),
                    ("on_deposit", "Sur acompte"),
                    ("on_production_progress", "À l'avancement de production"),
                ],
                default="on_ordered_qty",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="source",
            field=models.CharField(
                choices=[
                    ("stock", "Sur stock"),
                    ("production", "À produire"),
                    ("achat", "À acheter"),
                ],
                default="stock",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="salesquotation",
            name="incoterm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW — À l'usine"),
                    ("FOB", "FOB — Franco à bord"),
                    ("CIF", "CIF — Coût, assurance et fret"),
                    ("DAP", "DAP — Rendu au lieu de destination"),
                    ("DDP", "DDP — Rendu droits acquittés"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="salesquotation",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyé"),
                    ("accepted", "Accepté"),
                    ("declined", "Refusé"),
                    ("expired", "Expiré"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="salesquotationline",
            name="source",
            field=models.CharField(
                choices=[
                    ("stock", "Sur stock"),
                    ("production", "À produire"),
                    ("achat", "À acheter"),
                ],
                default="stock",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="salestarget",
            name="scope",
            field=models.CharField(
                choices=[
                    ("company", "Entreprise"),
                    ("team", "Équipe"),
                    ("salesperson", "Commercial"),
                ],
                default="company",
                max_length=16,
            ),
        ),
    ]
