# Generated by Django 5.2.17 on 2026-08-29 06:13

import apps.core.db.uuid7
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0017_savedtableview_shared_with_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinLoanApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "investissement_ct_mt",
                                "Investissement court/moyen terme",
                            ),
                            ("investissement_lt", "Investissement long terme"),
                            ("fonctionnement", "Fonctionnement"),
                            ("credoc", "Credit documentaire (CREDOC)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("bank_partner_id", models.UUIDField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                (
                    "amount_requested_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("currency", models.CharField(default="MGA", max_length=3)),
                ("duration_months", models.PositiveIntegerField()),
                ("purpose", models.TextField(blank=True)),
                (
                    "own_contribution_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30"), max_digits=5
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Demande (brouillon)"),
                            ("submitted", "Soumis a la banque"),
                            ("accepted", "Accepte"),
                            ("rejected", "Rejete"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fin_loan_application",
            },
        ),
        migrations.CreateModel(
            name="FinFinancingPlanLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fonds_propres", "Fonds propres"),
                            ("emprunt_sollicite", "Emprunt sollicite"),
                            ("autre", "Autre source"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("amount_mga", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financing_plan_lines",
                        to="financing.finloanapplication",
                    ),
                ),
            ],
            options={
                "db_table": "fin_financing_plan_line",
            },
        ),
    ]
