# Generated by Django 5.2.17 on 2026-08-29 06:40

import apps.core.db.uuid7
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_savedtableview_shared_with_role"),
        ("financing", "0002_finforecastscenario_finforecastscenarioline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinCredoc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("purchase_order_id", models.UUIDField()),
                ("log_shipment_id", models.UUIDField(blank=True, null=True)),
                ("bank", models.CharField(max_length=255)),
                ("advising_bank", models.CharField(blank=True, max_length=255)),
                ("beneficiary", models.CharField(max_length=255)),
                ("amount_mga", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="MGA", max_length=3)),
                ("validity_date", models.DateField()),
                (
                    "incoterm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW — A l'usine"),
                            ("FOB", "FOB — Franco a bord"),
                            ("CIF", "CIF — Cout, assurance et fret"),
                            ("DAP", "DAP — Rendu au lieu de destination"),
                            ("DDP", "DDP — Rendu droits acquittes"),
                        ],
                        max_length=8,
                    ),
                ),
                ("documents_required", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("demande", "Demande"),
                            ("ouvert", "Ouvert"),
                            ("documents_recus", "Documents recus"),
                            ("paye", "Paye"),
                            ("clos", "Clos"),
                        ],
                        default="demande",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credocs",
                        to="financing.finloanapplication",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fin_credoc",
            },
        ),
    ]
