# Generated by Django 5.2.17 on 2026-09-01 06:17

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financing", "0003_fincredoc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fincredoc",
            name="incoterm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW — A l'usine"),
                    ("FOB", "FOB — Franco a bord"),
                    ("CIF", "CIF — Coût, assurance et fret"),
                    ("DAP", "DAP — Rendu au lieu de destination"),
                    ("DDP", "DDP — Rendu droits acquittes"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="fincredoc",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("demande", "Demande"),
                    ("ouvert", "Ouvert"),
                    ("documents_recus", "Documents reçus"),
                    ("paye", "Paye"),
                    ("clos", "Clos"),
                ],
                default="demande",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="finforecastscenarioline",
            name="source",
            field=models.CharField(
                choices=[
                    ("manuel", "Saisie manuelle"),
                    ("payroll_projection", "Projection masse salariale (payroll)"),
                    ("treasury_forecast", "Trésorerie prévisionnelle (accounting)"),
                ],
                default="manuel",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="finforecastscenarioline",
            name="statement_type",
            field=models.CharField(
                choices=[
                    ("income_statement", "Compte de résultat prévisionnel"),
                    ("balance_sheet", "Bilan prévisionnel"),
                    ("cash_flow", "Trésorerie prévisionnelle"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="finguarantee",
            name="formalization_status",
            field=models.CharField(
                choices=[
                    ("a_formaliser", "A formaliser"),
                    ("en_cours", "En cours de formalisation"),
                    ("formalisee", "Formalisée"),
                ],
                default="a_formaliser",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="finguarantee",
            name="type",
            field=models.CharField(
                choices=[
                    ("hypotheque", "Hypothèque"),
                    ("nantissement", "Nantissement"),
                    ("caution_personnelle", "Caution personnelle"),
                    ("caution_bancaire", "Caution bancaire"),
                    ("gage", "Gage"),
                    ("autre", "Autre sûreté"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="finloanapplication",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Demande (brouillon)"),
                    ("submitted", "Soumis a la banque"),
                    ("accepted", "Accepte"),
                    ("rejected", "Rejeté"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="finloanapplication",
            name="type",
            field=models.CharField(
                choices=[
                    ("investissement_ct_mt", "Investissement court/moyen terme"),
                    ("investissement_lt", "Investissement long terme"),
                    ("fonctionnement", "Fonctionnement"),
                    ("credoc", "Crédit documentaire (CREDOC)"),
                ],
                max_length=32,
            ),
        ),
    ]
