# Generated by Django 5.2.17 on 2026-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financing", "0004_alter_fincredoc_incoterm_alter_fincredoc_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fincredoc",
            name="amount_foreign",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
    ]
