# Generated by Django 5.2.17 on 2026-09-03 19:14

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0028_regulatoryparameter_validation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("client_uuid", models.UUIDField()),
                ("number", models.CharField(blank=True, db_index=True, max_length=32)),
                ("local_sequence", models.PositiveIntegerField()),
                (
                    "order_type",
                    models.CharField(
                        choices=[("sale", "Vente"), ("return", "Retour / avoir")],
                        default="sale",
                        max_length=8,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("invoice", "Facture nominative"),
                        ],
                        default="ticket",
                        max_length=8,
                    ),
                ),
                ("partner_id", models.UUIDField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("validated", "Validée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("online", "En ligne"),
                            ("offline", "Hors ligne (synchronisée)"),
                        ],
                        default="online",
                        max_length=8,
                    ),
                ),
                (
                    "amount_untaxed",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_tax",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("reprint_count", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="pos.posorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pos_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "line_type",
                    models.CharField(
                        choices=[("product", "Produit"), ("service", "Service")],
                        default="product",
                        max_length=16,
                    ),
                ),
                ("variant_id", models.UUIDField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=1, max_digits=18),
                ),
                ("uom", models.CharField(blank=True, max_length=16)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("tax_id", models.UUIDField(blank=True, null=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "service_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("forfait", "Forfait"),
                            ("temps_passe", "Temps passé"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_deposit", models.BooleanField(default=False)),
                ("stock_move_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pos.posorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pos_order_line",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="PosPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("mobile_money", "Mobile money"),
                            ("card", "Carte"),
                            ("cheque", "Chèque"),
                            ("credit_note", "Avoir"),
                        ],
                        max_length=16,
                    ),
                ),
                ("requires_reference", models.BooleanField(default=False)),
                (
                    "default_account_type",
                    models.CharField(
                        choices=[
                            ("cash", "Caisse"),
                            ("bank", "Banque / monnaie électronique"),
                        ],
                        default="cash",
                        max_length=16,
                    ),
                ),
                ("account_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pos_payment_method",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PosPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("received_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="pos.posorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pos.pospaymentmethod",
                    ),
                ),
            ],
            options={
                "db_table": "pos_payment",
                "ordering": ["received_at"],
            },
        ),
        migrations.CreateModel(
            name="PosRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=120)),
                ("warehouse_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pos_register",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="posorder",
            name="register",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pos.posregister",
            ),
        ),
        migrations.CreateModel(
            name="PosSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Ouverte"), ("closed", "Clôturée")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_cash_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "closing_cash_counted",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "closing_cash_expected",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cash_variance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("cash_variance_reason", models.CharField(blank=True, max_length=255)),
                ("closing_move_id", models.UUIDField(blank=True, null=True)),
                ("local_sequence_last", models.PositiveIntegerField(default=0)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="pos.posregister",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pos_session",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="posorder",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pos.possession",
            ),
        ),
        migrations.CreateModel(
            name="PosCashMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Entrée"), ("out", "Sortie")], max_length=8
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_movements",
                        to="pos.possession",
                    ),
                ),
            ],
            options={
                "db_table": "pos_cash_movement",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("client_uuid", models.UUIDField()),
                ("local_sequence", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "Acceptée"),
                            ("duplicate", "Doublon ignoré"),
                            ("rejected", "Rejetée"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("synced_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.posorder",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pos.posregister",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.possession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pos_sync_log",
                "ordering": ["-synced_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="pospaymentmethod",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"),
                name="uniq_pos_payment_method_code_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="posregister",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_pos_register_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="posorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_uuid"),
                name="uniq_pos_order_client_uuid_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="posorder",
            constraint=models.UniqueConstraint(
                fields=("session", "local_sequence"),
                name="uniq_pos_order_local_sequence_per_session",
            ),
        ),
    ]
