# Generated by Django 5.2.17 on 2026-08-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_catalogstandard_catalogcertification"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsupplierinfo",
            name="min_qty",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="productsupplierinfo",
            name="origin",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("import_chine", "Import Chine"),
                    ("import_autre", "Import autre"),
                    ("en_ligne", "En ligne"),
                ],
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="productsupplierinfo",
            name="priority",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
