# Generated by Django 5.2.17 on 2026-08-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_productsupplierinfo_min_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_placeholder",
            field=models.BooleanField(default=False),
        ),
    ]
