# Generated by Django 5.2.17 on 2026-08-29 08:20

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_catalogsectorspec"),
        ("core", "0017_savedtableview_shared_with_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="hex_approximation",
            field=models.CharField(
                blank=True,
                help_text="Approximation hex saisie manuellement — jamais une valeur sourcee du nuancier Pantone (reserve legale, cf. plan).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="pantone_code",
            field=models.CharField(
                blank=True, help_text="Format 'NN-NNNN TCX'.", max_length=16
            ),
        ),
        migrations.CreateModel(
            name="CatalogMaterialReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("naturelle_cellulosique", "Naturelle cellulosique"),
                            ("naturelle_proteique", "Naturelle proteique"),
                            ("synthetique_hydrophobe", "Synthetique hydrophobe"),
                            ("synthetique_fr", "Synthetique ignifuge (FR)"),
                            ("melange", "Melange"),
                            ("caoutchouc", "Caoutchouc"),
                            ("membrane", "Membrane technique"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "typical_gsm_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grammage min, g/m²",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "typical_gsm_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grammage max, g/m²",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("usage_notes", models.TextField(blank=True)),
                ("supplier_reference", models.CharField(blank=True, max_length=150)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "catalog_material_reference",
            },
        ),
    ]
