# Generated by Django 5.2.17 on 2026-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_catalogcustomizationoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogcertification",
            name="status",
            field=models.CharField(
                choices=[
                    ("vise", "Visee"),
                    ("en_cours", "En cours"),
                    ("obtenue", "Obtenue"),
                    ("expiree", "Expiree"),
                ],
                default="obtenue",
                max_length=16,
            ),
        ),
    ]
