# Generated by Django 5.2.17 on 2026-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_catalogcertification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcertification",
            name="status",
            field=models.CharField(
                choices=[
                    ("vise", "Visée"),
                    ("en_cours", "En cours"),
                    ("obtenue", "Obtenue"),
                    ("expiree", "Expirée"),
                ],
                default="obtenue",
                max_length=16,
            ),
        ),
    ]
