# Generated by Django 5.2.17 on 2026-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_catalogcertification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="is_sellable",
            field=models.BooleanField(default=True),
        ),
    ]
