# Generated by Django 5.2.17 on 2026-09-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_producttemplate_is_sellable"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="ean13",
            field=models.CharField(blank=True, db_index=True, max_length=13),
        ),
    ]
