# Generated by Django 5.2.17 on 2026-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_productvariant_ean13"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_lot_tracked",
            field=models.BooleanField(default=False),
        ),
    ]
