# Generated by Django 5.2.17 on 2026-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_catalog_guards_uom_and_lot_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="requires_certificate_of_analysis",
            field=models.BooleanField(default=False),
        ),
    ]
