# Generated by Django 5.2.17 on 2026-08-26 22:44

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0015_tenant_fiscal_regime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatMeasurementPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                ("abbreviation", models.CharField(blank=True, max_length=16)),
                (
                    "unit",
                    models.CharField(
                        choices=[("cm", "cm"), ("mm", "mm"), ("inch", "inch")],
                        default="cm",
                        max_length=8,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("largeur", "Largeur"),
                            ("longueur", "Longueur"),
                            ("circonference", "Circonference"),
                            ("angle", "Angle"),
                        ],
                        default="longueur",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("illustration", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pat_measurement_point",
            },
        ),
        migrations.CreateModel(
            name="PatSizeChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                (
                    "garment_type",
                    models.CharField(
                        choices=[
                            ("chemise", "Chemise"),
                            ("pantalon", "Pantalon"),
                            ("robe", "Robe"),
                            ("veste", "Veste"),
                            ("jupe", "Jupe"),
                            ("tshirt", "T-shirt"),
                            ("combinaison", "Combinaison"),
                            ("accessoire", "Accessoire"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("unisexe", "Unisexe"),
                            ("enfant", "Enfant"),
                        ],
                        default="unisexe",
                        max_length=16,
                    ),
                ),
                (
                    "region_standard",
                    models.CharField(
                        choices=[
                            ("EU", "EU"),
                            ("US", "US"),
                            ("UK", "UK"),
                            ("FR", "FR"),
                            ("custom", "Personnalise"),
                        ],
                        default="custom",
                        max_length=16,
                    ),
                ),
                ("sizes", models.JSONField(default=list)),
                ("base_size", models.CharField(max_length=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pat_size_chart",
            },
        ),
        migrations.CreateModel(
            name="PatGradingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("increment_fixe", "Increment fixe"),
                            ("increment_progressif", "Increment progressif"),
                            ("pourcentage", "Pourcentage"),
                            ("formule", "Formule"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("formula", models.CharField(blank=True, max_length=255)),
                ("from_size", models.CharField(max_length=16)),
                ("to_size", models.CharField(max_length=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measurement_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="patronage.patmeasurementpoint",
                    ),
                ),
                (
                    "size_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_rules",
                        to="patronage.patsizechart",
                    ),
                ),
            ],
            options={
                "db_table": "pat_grading_rule",
            },
        ),
        migrations.CreateModel(
            name="PatSizeChartValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("size", models.CharField(max_length=16)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tolerance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measurement_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="patronage.patmeasurementpoint",
                    ),
                ),
                (
                    "size_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="patronage.patsizechart",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pat_size_chart_value",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("size_chart", "measurement_point", "size"),
                        name="uniq_pat_size_chart_value",
                    )
                ],
            },
        ),
    ]
