# Generated by Django 5.2.17 on 2026-08-26 22:54

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_tenant_fiscal_regime"),
        ("patronage", "0002_patpattern_patpatternpiece_patpiecegeometry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatMarker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fabric_width_cm",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("size_ratio", models.JSONField(default=dict)),
                (
                    "length_m",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "efficiency_pct",
                    models.DecimalField(decimal_places=2, default=85, max_digits=5),
                ),
                ("svg", models.TextField(blank=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="patronage.patpattern",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pat_marker",
            },
        ),
        migrations.CreateModel(
            name="PatConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("size", models.CharField(max_length=16)),
                ("material_variant_id", models.UUIDField()),
                (
                    "length_m",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("width_cm", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "area_m2",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "waste_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("calcul", "Calcul"),
                            ("saisie", "Saisie"),
                            ("placement", "Placement"),
                        ],
                        default="calcul",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="patronage.patpattern",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pat_consumption",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pattern", "size", "material_variant_id"),
                        name="uniq_pat_consumption",
                    )
                ],
            },
        ),
    ]
