# Generated by Django 5.2.17 on 2026-09-03 22:42

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0028_regulatoryparameter_validation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForExceptionalPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[
                            ("famille", "Famille"),
                            ("article", "Article"),
                            ("client", "Client"),
                            ("canal", "Canal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("dimension_value", models.CharField(max_length=64)),
                (
                    "period",
                    models.DateField(
                        help_text="Premier jour de la période (maille mensuelle)"
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "for_exceptional_point",
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant",
                            "dimension_type",
                            "dimension_value",
                            "period",
                        ),
                        name="uniq_for_exceptional_point",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ForHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "for_holiday",
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "date"), name="uniq_for_holiday_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ForPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField()),
                ("published_at", models.DateTimeField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("snapshot", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "for_publication",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "version"),
                        name="uniq_for_publication_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ForSeriesForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[
                            ("famille", "Famille"),
                            ("article", "Article"),
                            ("client", "Client"),
                            ("canal", "Canal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("dimension_value", models.CharField(max_length=64)),
                (
                    "period",
                    models.DateField(help_text="Premier jour de la période prévue"),
                ),
                (
                    "reference_naive_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("reference_naive_beats_selected", models.BooleanField(default=False)),
                (
                    "selected_model",
                    models.CharField(
                        choices=[
                            ("naive_saisonnier", "Référence naïve saisonnière"),
                            ("moyenne_mobile", "Moyenne mobile"),
                            ("lissage_simple", "Lissage exponentiel simple"),
                            ("lissage_double", "Lissage exponentiel double"),
                            ("lissage_triple", "Lissage exponentiel triple"),
                            ("regression_calendaire", "Régression calendaire"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "selected_model_score",
                    models.DecimalField(decimal_places=4, max_digits=9),
                ),
                ("rejected_models", models.JSONField(blank=True, default=list)),
                ("test_window_start", models.DateField()),
                ("test_window_end", models.DateField()),
                (
                    "insufficient_history_for_seasonality",
                    models.BooleanField(default=False),
                ),
                (
                    "error_mae_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "error_weighted_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "error_bias_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "statistical_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "adjusted_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("adjustment_history", models.JSONField(blank=True, default=list)),
                (
                    "adjustment_error_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "statistical_error_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                ("computed_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "for_series_forecast",
                "ordering": ["dimension_type", "dimension_value", "period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant",
                            "dimension_type",
                            "dimension_value",
                            "period",
                        ),
                        name="uniq_for_series_forecast",
                    )
                ],
            },
        ),
    ]
