# Generated by Django 5.2.17 on 2026-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_crmactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmpipeline",
            name="stagnant_after_days",
            field=models.PositiveSmallIntegerField(default=21),
        ),
    ]
