# Generated by Django 5.2.17 on 2026-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_libelles_semes_accentues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Appel"),
                    ("visit", "Visite"),
                    ("email", "Courriel"),
                    ("follow_up", "Relance"),
                    ("meeting", "Réunion"),
                ],
                max_length=16,
            ),
        ),
    ]
