# Generated by Django 5.2.17 on 2026-08-26 18:43

import apps.core.db.uuid7
import apps.core.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_sampletenantscopedrecord"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="RoleProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("simple_mode_default", models.BooleanField(default=False)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_profile",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "core_role_profile",
            },
        ),
    ]
