# Generated by Django 5.2.17 on 2026-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_sampletenantscopedrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrule",
            name="escalate_after",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="fallback_approver_role",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
