# Generated by Django 5.2.17 on 2026-08-26 19:17

import apps.core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_approvalrule_escalate_after_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("dispatched", "Distribué"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_event_log",
            },
        ),
    ]
