# Generated by Django 5.2.17 on 2026-08-26 19:44

import apps.core.db.uuid7
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0011_seed_country_defaults_madagascar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("notification_type", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("app", "Application"),
                            ("email", "E-mail"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="app",
                        max_length=16,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grouped_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Sortant"), ("inbound", "Entrant")],
                        max_length=16,
                    ),
                ),
                ("phone_number", models.CharField(max_length=32)),
                ("body", models.TextField(blank=True)),
                ("template_name", models.CharField(blank=True, max_length=100)),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sent", "Envoyé"),
                            ("delivered", "Distribué"),
                            ("failed", "Échoué"),
                            ("received", "Reçu"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="core.notification",
                    ),
                ),
            ],
            options={
                "db_table": "core_whatsapp_message",
            },
        ),
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("text", models.TextField()),
                ("url", models.CharField(blank=True, max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "core_search_document",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="core_search_search__43ae6a_gin"
                    )
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
