# Generated by Django 5.2.17 on 2026-08-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_savedtableview"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="fiscal_regime",
            field=models.CharField(
                choices=[
                    ("synthetique", "Synthétique (impôt forfaitaire)"),
                    ("reel_sans_tva", "Réel, sans assujettissement TVA"),
                    ("reel_avec_tva", "Réel, avec assujettissement TVA"),
                ],
                default="reel_avec_tva",
                max_length=16,
            ),
        ),
    ]
