# Generated by Django 5.2.17 on 2026-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_tenant_fiscal_regime"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="vat_opted_in",
            field=models.BooleanField(default=False),
        ),
    ]
