# Generated by Django 5.2.17 on 2026-08-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedtableview",
            name="shared_with_role",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
