# Generated by Django 5.2.17 on 2026-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_qltchecklisttemplate_qltinspection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("fournisseur", "Fournisseur"),
                    ("production", "Production"),
                    ("logistique", "Logistique"),
                    ("financier", "Financier"),
                    ("qualite", "Qualite"),
                    ("rh", "Ressources humaines"),
                    ("projet", "Projet"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=16,
            ),
        ),
    ]
