# Generated by Django 5.2.17 on 2026-09-01 04:57
# Derive manuellement de la migration auto-generee : isole une derive
# preexistante (accents manquants dans les libelles `choices` de
# `RiskItem`, deja corriges cote modele par un chantier anterieur ACC4-6
# mais jamais reflete dans une migration) de la migration UXR1 suivante
# (0022), qui, elle, porte reellement le contenu de ce chantier.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_riskitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("fournisseur", "Fournisseur"),
                    ("production", "Production"),
                    ("logistique", "Logistique"),
                    ("financier", "Financier"),
                    ("qualite", "Qualité"),
                    ("rh", "Ressources humaines"),
                    ("projet", "Projet"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="riskitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Ouvert"),
                    ("mitigating", "En atténuation"),
                    ("closed", "Clôturé"),
                ],
                default="open",
                max_length=16,
            ),
        ),
    ]
