# Generated by Django 5.2.17 on 2026-09-01 04:57
# UXR1 — gestion des utilisateurs : nouvelle permission personnalisee
# `core.manage_users`, `User.preferred_language` gagne des `choices`
# fr/en (sans transformation de donnees, "fr"/"en" deja valides), et le
# nouveau modele `UserEmailChangeRequest` (confirmation d'e-mail par
# lien a jeton, cf. `apps/core/models/user.py` pour la docstring
# complete).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_riskitem_category_alter_riskitem_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("manage_users", "Peut gérer les comptes utilisateurs")],
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="UserEmailChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("new_email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.CharField(db_index=True, editable=False, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Admin a l'origine du changement, ou None si l'utilisateur "
                            "a lui-meme demande le changement."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_user_email_change_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
