# Generated by Django 5.2.17 on 2026-09-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_tenantdataoperation_tenantbackupschedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantdataoperation",
            options={"ordering": ["-created_at"]},
        ),
    ]
