# Generated by Django 5.2.17 on 2026-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_tenantdataoperation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
