# Generated by Django 5.2.17 on 2026-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_chattermessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="density",
            field=models.CharField(
                choices=[("comfortable", "Confortable"), ("compact", "Compacte")],
                default="comfortable",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "Clair"), ("dark", "Sombre"), ("system", "Système")],
                default="system",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English"), ("mg", "Malagasy")],
                default="fr",
                max_length=5,
            ),
        ),
    ]
