# Generated by Django 5.2.17 on 2026-09-03 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_user_density_user_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulatoryparameter",
            name="statut_validation",
            field=models.CharField(
                choices=[
                    ("non_valide", "Non validé"),
                    ("valide_oecfm", "Validé OECFM"),
                ],
                default="non_valide",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="regulatoryparameter",
            name="valide_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="regulatoryparameter",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="regulatoryparameter",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
