# Generated by Django 5.2.17 on 2026-09-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_regulatoryparameter_validation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_cost_alert_threshold_pct",
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_cost_cap_hard_stop",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_monthly_cost_cap_ariary",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="category",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="conversation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="cost_ariary",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="variables",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
