# Generated by Django 5.2.17 on 2026-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_hash_email_change_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="legal_mentions",
            field=models.TextField(blank=True, verbose_name="mentions légales"),
        ),
    ]
