# Generated by Django 5.2.17 on 2026-09-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_tenant_legal_mentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_max_messages_per_recipient_per_day",
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="error_message",
            field=models.TextField(blank=True),
        ),
    ]
