# Generated by Django 5.2.17 on 2026-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_tenant_whatsapp_max_messages_per_recipient_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_phone_number_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("whatsapp_phone_number_id", ""), _negated=True),
                fields=("whatsapp_phone_number_id",),
                name="uniq_tenant_whatsapp_phone_number_id",
            ),
        ),
    ]
