# Generated by Django 5.2.17 on 2026-09-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_tenant_whatsapp_phone_number_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="cost_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("conversation", "À la conversation"),
                    ("message", "Au message"),
                ],
                max_length=16,
            ),
        ),
    ]
