# Generated by Django 5.2.17 on 2026-09-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_whatsappmessage_cost_unit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["expires_at"], name="idx_core_idemp_expires"),
        ),
    ]
