# Generated by Django 5.2.17 on 2026-09-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_idempotencykey_idx_core_idemp_expires"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="whatsappmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("direction", "inbound"),
                    models.Q(("provider_message_id", ""), _negated=True),
                ),
                fields=("tenant_id", "provider_message_id"),
                name="uniq_wa_inbound_provider_message_id",
            ),
        ),
    ]
