# Generated by Django 5.2.17 on 2026-09-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_whatsappmessage_uniq_wa_inbound_provider_message_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="idempotencykey",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="idempotencykey",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "user_id", "key"),
                name="uniq_core_idemp_tenant_user_key",
                nulls_distinct=False,
            ),
        ),
    ]
