"""T3 (l.224, EFA-1) — l'identifiant fiscal de l'EMETTEUR entre dans le
meme regime que celui du tiers.

Une facture soumise a une administration porte deux identites : celle du
client et celle de celui qui l'emet. EFA-1 les exige toutes les deux
(« un champ obligatoire manquant bloque la soumission et designe le
champ »). `Tenant.nif` etait une chaine libre, `Tenant.stat` n'existait
pas ; ils suivent desormais le format declare par pays
(`core.services.fiscal_identifiers`), applique dans `Tenant.save()`.

**Aucune migration de donnees, et c'est delibere.** Normaliser en masse
des identifiants existants les REECRIRAIT sans que personne l'ait
demande — et l'une des deux formes en presence peut etre la forme
officielle. La commande `audit_fiscal_identifiers` (T3) chiffre d'abord
ce qui ne passe pas ; la correction reste une decision humaine, et c'est
exactement l'accompagnement que le cahier met a la charge du client.
"""

# Generated by Django 5.2.17 on 2026-09-08 15:27

import apps.core.services.fiscal_identifiers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_remove_country_defaults_holidays"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stat",
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[apps.core.services.fiscal_identifiers.validate_partner_stat],
                verbose_name="numéro statistique",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="nif",
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[apps.core.services.fiscal_identifiers.validate_partner_nif],
                verbose_name="NIF",
            ),
        ),
    ]
