# Generated by Django 5.2.17 on 2026-09-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_tenant_stat_alter_tenant_nif"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="mobile_payment_provider",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
