# Generated by Django 5.2.17 on 2026-08-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0003_mrporder_mrpordercomponent_mrpsubcontractorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrporder",
            name="cost_labor_planned_mga",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="mrporder",
            name="cost_material_planned_mga",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="mrporder",
            name="cost_overhead_planned_mga",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="mrporder",
            name="cost_total_planned_mga",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="mrpordercomponent",
            name="variance_reason",
            field=models.TextField(blank=True),
        ),
    ]
