# Generated by Django 5.2.17 on 2026-08-26 22:27

import apps.core.db.uuid7
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_tenant_fiscal_regime"),
        ("mrp", "0005_mrpcra_mrpcri_mrpscrap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MrpBomLineState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("a_commander", "A commander"),
                            ("echantillon_demande", "Echantillon demande"),
                            ("echantillon_evalue", "Echantillon evalue"),
                            ("fournisseur_valide", "Fournisseur valide"),
                            ("commande", "Commande"),
                            ("recue", "Recue"),
                            ("controle_qualite", "Controle qualite"),
                            ("disponible", "Disponible"),
                            ("en_production", "En production"),
                            ("consommee", "Consommee"),
                            ("rupture", "Rupture"),
                            ("rejetee", "Rejetee"),
                        ],
                        default="a_commander",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_state",
                        to="mrp.mrpordercomponent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mrp_bom_line_state",
            },
        ),
        migrations.CreateModel(
            name="MrpMaintenancePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendaire"),
                            ("hours", "Horaire (heures machine)"),
                        ],
                        default="calendar",
                        max_length=16,
                    ),
                ),
                ("interval_days", models.PositiveIntegerField(blank=True, null=True)),
                ("interval_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("last_done_at", models.DateField(blank=True, null=True)),
                ("next_due_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workcenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_plans",
                        to="mrp.mrpworkcenter",
                    ),
                ),
            ],
            options={
                "db_table": "mrp_maintenance_plan",
            },
        ),
        migrations.CreateModel(
            name="MrpSampleRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.UUIDField()),
                ("component_template_id", models.UUIDField()),
                ("date_requested", models.DateField()),
                ("date_received", models.DateField(blank=True, null=True)),
                ("evaluation_notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Demande"),
                            ("received", "Recu"),
                            ("evaluated", "Evalue"),
                            ("approved", "Approuve"),
                            ("rejected", "Rejete"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mrp_sample_request",
            },
        ),
        migrations.CreateModel(
            name="MrpSupplierEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.UUIDField()),
                ("component_template_id", models.UUIDField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "score_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "score_quality",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "score_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "score_delay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "score_conformity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("weight_quantity", models.PositiveSmallIntegerField(default=18)),
                ("weight_quality", models.PositiveSmallIntegerField(default=30)),
                ("weight_cost", models.PositiveSmallIntegerField(default=27)),
                ("weight_delay", models.PositiveSmallIntegerField(default=13)),
                ("weight_conformity", models.PositiveSmallIntegerField(default=12)),
                ("conformity_blocking", models.BooleanField(default=False)),
                (
                    "weighted_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mrp_supplier_evaluation",
            },
        ),
    ]
