# Generated by Django 5.2.17 on 2026-08-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0006_mrpbomlinestate_mrpmaintenanceplan_mrpsamplerequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrpcri",
            name="pattern_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
