# Generated by Django 5.2.17 on 2026-09-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0007_mrpcri_pattern_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrporder",
            name="output_lot_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
