# Generated by Django 5.2.17 on 2026-09-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0008_mrporder_output_lot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrpordercomponent",
            name="reservation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
