# Generated by Django 5.2.17 on 2026-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0009_mrpordercomponent_reservation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrpsubcontractorder",
            name="send_move_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mrpsubcontractorder",
            name="variant_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
