# Generated by Django 5.2.17 on 2026-09-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0010_mrpsubcontractorder_send_move_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrpbom",
            name="by_products",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="mrpbom",
            name="expected_yield_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mrpbom",
            name="type",
            field=models.CharField(
                choices=[
                    ("manufacture", "Fabrication"),
                    ("kit", "Kit"),
                    ("subcontract", "Sous-traitance"),
                    ("process", "Process (agroalimentaire)"),
                ],
                default="manufacture",
                max_length=16,
            ),
        ),
    ]
