# Generated by Django 5.2.17 on 2026-09-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0011_mrpbom_by_products_mrpbom_expected_yield_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrporder",
            name="cost_subcontracting_mga",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="mrporder",
            name="material_reconciliation_reason",
            field=models.TextField(blank=True),
        ),
    ]
