# Generated by Django 5.2.17 on 2026-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0012_mrporder_cost_subcontracting_mga_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrpordercomponent",
            name="consumed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
