# Generated by Django 5.2.17 on 2026-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="is_placeholder",
            field=models.BooleanField(default=False),
        ),
    ]
