# Generated by Django 5.2.17 on 2026-09-02 06:35

import apps.core.db.uuid7
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_tenant_address_tenant_email_tenant_logo_tenant_phone"),
        ("partners", "0002_partner_is_placeholder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("client", "Client"),
                        ("supplier", "Fournisseur"),
                        ("carrier", "Transporteur"),
                        ("subcontractor", "Sous-traitant"),
                        ("associate", "Associé"),
                        ("collaborator", "Collaborateur"),
                        ("bank", "Banque"),
                    ],
                    max_length=20,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="PartnerContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client", "Client"),
                            ("supplier", "Fournisseur"),
                            ("carrier", "Transporteur"),
                            ("subcontractor", "Sous-traitant"),
                            ("associate", "Associé"),
                            ("collaborator", "Collaborateur"),
                            ("bank", "Banque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="partners.partner",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "partners_contact",
            },
        ),
    ]
