"""T3 (l.224, EFA-1) — le referentiel tiers cesse d'accepter n'importe quoi.

**Le defaut ferme.** `Partner.nif` etait un `CharField(max_length=32,
blank=True)` sans le moindre validateur, ecrit par six surfaces sans
controle. Le numero statistique, que toute administration fiscale demande
a cote du NIF, n'existait pas du tout.

**Trois champs, trois raisons distinctes.**

- `stat` : la seconde moitie de l'identite fiscale. Sans lui la soumission
  serait incomplete au moment precis ou elle devient bloquante.
- `fiscal_verification_state` : le resultat de l'interrogation du
  referentiel (OP8). Un CHOIX ferme et non un booleen — « jamais verifie »
  et « introuvable au referentiel » sont deux situations que le comptable
  traite differemment, et les confondre reviendrait a presenter une
  absence de verification comme un echec.
- `fiscal_verified_at` : la date. Le cahier exige pour OP8 une « mise en
  cache avec duree de validite » : une confirmation sans date ne peut pas
  expirer, donc n'est pas une mise en cache.

**Aucune migration de donnees.** Les identifiants deja saisis restent tels
quels : les normaliser en masse reecrirait la saisie de comptables sans
qu'ils l'aient demande. `audit_fiscal_identifiers` les chiffre, la
correction reste humaine — c'est le travail que le cahier met a la charge
du client, et le produit lui donne de quoi le mesurer avant qu'il ne
bloque quoi que ce soit.
"""

# Generated by Django 5.2.17 on 2026-09-08 15:27

import apps.core.services.fiscal_identifiers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0003_alter_partner_roles_partnercontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="fiscal_verification_state",
            field=models.CharField(
                choices=[
                    ("non_verifie", "Non vérifié"),
                    ("confirme", "Confirmé par le référentiel"),
                    ("introuvable", "Introuvable au référentiel"),
                    ("referentiel_indisponible", "Référentiel indisponible"),
                ],
                default="non_verifie",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="fiscal_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="stat",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                validators=[apps.core.services.fiscal_identifiers.validate_partner_stat],
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="nif",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                validators=[apps.core.services.fiscal_identifiers.validate_partner_nif],
            ),
        ),
    ]
