# Generated by Django 5.2.17 on 2026-09-03 21:41

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0028_regulatoryparameter_validation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnDimArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("variant_id", models.UUIDField()),
                ("template_id", models.UUIDField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("libelle", models.CharField(blank=True, max_length=200)),
                ("categorie_nom", models.CharField(blank=True, max_length=120)),
                ("is_sellable", models.BooleanField(default=True)),
                ("is_placeholder", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_dim_article",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="AnDimTemps",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("annee", models.PositiveSmallIntegerField()),
                ("trimestre", models.PositiveSmallIntegerField()),
                ("mois", models.PositiveSmallIntegerField()),
                ("mois_libelle", models.CharField(max_length=16)),
                ("semaine_iso", models.PositiveSmallIntegerField()),
                ("jour_du_mois", models.PositiveSmallIntegerField()),
                (
                    "jour_semaine_iso",
                    models.PositiveSmallIntegerField(
                        help_text="1=lundi ... 7=dimanche"
                    ),
                ),
                ("jour_semaine_libelle", models.CharField(max_length=16)),
                ("est_weekend", models.BooleanField(default=False)),
                ("exercice_fiscal", models.PositiveSmallIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_dim_temps",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="AnDimTiers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.UUIDField()),
                ("code", models.CharField(blank=True, max_length=32)),
                ("nom", models.CharField(max_length=200)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("is_placeholder", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_dim_tiers",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="AnFactEcriture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_line_id", models.UUIDField()),
                ("compte_code", models.CharField(blank=True, max_length=20)),
                ("compte_libelle", models.CharField(blank=True, max_length=200)),
                (
                    "compte_classe_pcg",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("move_reference", models.CharField(blank=True, max_length=64)),
                ("move_type", models.CharField(blank=True, max_length=24)),
                (
                    "debit_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "credit_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "solde_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecritures",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "dim_tiers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures",
                        to="analytics.andimtiers",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_ecriture",
            },
        ),
        migrations.CreateModel(
            name="AnFactEncaissement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_payment_id", models.UUIDField()),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("direction", models.CharField(blank=True, max_length=16)),
                ("method", models.CharField(blank=True, max_length=16)),
                (
                    "montant_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("state", models.CharField(blank=True, max_length=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaissements",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "dim_tiers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaissements",
                        to="analytics.andimtiers",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_encaissement",
            },
        ),
        migrations.CreateModel(
            name="AnFactTicketPos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_line_id", models.UUIDField()),
                ("point_vente_code", models.CharField(blank=True, max_length=16)),
                ("point_vente_nom", models.CharField(blank=True, max_length=120)),
                ("ticket_number", models.CharField(blank=True, max_length=32)),
                ("order_type", models.CharField(blank=True, max_length=8)),
                ("line_type", models.CharField(blank=True, max_length=16)),
                ("canal", models.CharField(default="pos", max_length=16)),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "unit_price_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "montant_ht_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "montant_tva_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "montant_ttc_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_pos",
                        to="analytics.andimarticle",
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets_pos",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "dim_tiers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_pos",
                        to="analytics.andimtiers",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_ticket_pos",
            },
        ),
        migrations.CreateModel(
            name="AnFactVente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_line_id", models.UUIDField()),
                ("order_reference", models.CharField(blank=True, max_length=64)),
                ("order_state", models.CharField(blank=True, max_length=32)),
                ("canal", models.CharField(default="vente_directe", max_length=16)),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "unit_price_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "montant_ht_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "cost_estimate_mga",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "margin_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes",
                        to="analytics.andimarticle",
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "dim_tiers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes",
                        to="analytics.andimtiers",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_vente",
            },
        ),
        migrations.CreateModel(
            name="AnMetricDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("formule", models.TextField(blank=True)),
                ("unite", models.CharField(blank=True, max_length=16)),
                ("module_source", models.CharField(blank=True, max_length=32)),
                ("axes_autorises", models.JSONField(blank=True, default=list)),
                ("roles_autorises", models.JSONField(blank=True, default=list)),
                ("maille_minimale", models.CharField(blank=True, max_length=32)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("deprecie", "Déprécié"),
                        ],
                        default="brouillon",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("date_effet", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_metric_definition",
                "ordering": ["module_source", "code"],
            },
        ),
        migrations.CreateModel(
            name="AnRefreshRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En cours"),
                            ("success", "Succès"),
                            ("failed", "Échec"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("cron", "Planifié"), ("manual", "Manuel")],
                        default="cron",
                        max_length=16,
                    ),
                ),
                ("rows_processed", models.PositiveIntegerField(default=0)),
                ("reconciliation_ok", models.BooleanField(blank=True, null=True)),
                ("reconciliation_detail", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_refresh_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AnWarehouseState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_successful_refresh_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "watermark_sales_orderline",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "watermark_pos_orderline",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("watermark_acc_payment", models.DateTimeField(blank=True, null=True)),
                ("watermark_acc_moveline", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_warehouse_state",
            },
        ),
        migrations.AddConstraint(
            model_name="andimarticle",
            constraint=models.UniqueConstraint(
                fields=("tenant", "variant_id"), name="uniq_an_dim_article"
            ),
        ),
        migrations.AddIndex(
            model_name="andimtemps",
            index=models.Index(
                fields=["annee", "mois"], name="an_dim_temp_annee_51b2d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="andimtemps",
            constraint=models.UniqueConstraint(
                fields=("tenant", "date"), name="uniq_an_dim_temps_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="andimtiers",
            constraint=models.UniqueConstraint(
                fields=("tenant", "partner_id"), name="uniq_an_dim_tiers"
            ),
        ),
        migrations.AddIndex(
            model_name="anfactecriture",
            index=models.Index(
                fields=["dim_temps"], name="an_fact_ecr_dim_tem_8a3945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anfactecriture",
            index=models.Index(
                fields=["compte_code"], name="an_fact_ecr_compte__fd4ffc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anfactecriture",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_line_id"), name="uniq_an_fact_ecriture"
            ),
        ),
        migrations.AddIndex(
            model_name="anfactencaissement",
            index=models.Index(
                fields=["dim_temps"], name="an_fact_enc_dim_tem_c7b4c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anfactencaissement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_payment_id"), name="uniq_an_fact_encaissement"
            ),
        ),
        migrations.AddIndex(
            model_name="anfactticketpos",
            index=models.Index(
                fields=["dim_temps"], name="an_fact_tic_dim_tem_fbfedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anfactticketpos",
            index=models.Index(
                fields=["point_vente_code"], name="an_fact_tic_point_v_4a6054_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anfactticketpos",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_line_id"), name="uniq_an_fact_ticket_pos"
            ),
        ),
        migrations.AddIndex(
            model_name="anfactvente",
            index=models.Index(
                fields=["dim_temps"], name="an_fact_ven_dim_tem_9b4595_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anfactvente",
            index=models.Index(
                fields=["dim_tiers"], name="an_fact_ven_dim_tie_d847f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anfactvente",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_line_id"), name="uniq_an_fact_vente"
            ),
        ),
        migrations.AddConstraint(
            model_name="anmetricdefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_an_metric_definition"
            ),
        ),
        migrations.AddConstraint(
            model_name="anwarehousestate",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="uniq_an_warehouse_state_tenant"
            ),
        ),
    ]
