# Generated by Django 5.2.17 on 2026-09-03 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("core", "0028_regulatoryparameter_validation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anmetricdefinition",
            options={"ordering": ["module_source", "code", "-version"]},
        ),
        migrations.RemoveConstraint(
            model_name="anmetricdefinition",
            name="uniq_an_metric_definition",
        ),
        migrations.AddField(
            model_name="anmetricdefinition",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="anmetricdefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code", "version"),
                name="uniq_an_metric_definition_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="anmetricdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("tenant", "code"),
                name="uniq_an_metric_definition_current",
            ),
        ),
    ]
