# Generated by Django 5.2.17 on 2026-09-04 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_alter_anmetricdefinition_options_and_more"),
        ("core", "0029_tenant_whatsapp_cost_alert_threshold_pct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anwarehousestate",
            name="watermark_stk_move",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AnFactMouvementStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_move_id", models.UUIDField()),
                ("move_reference", models.CharField(blank=True, max_length=64)),
                ("move_type", models.CharField(blank=True, max_length=32)),
                ("lot_name", models.CharField(blank=True, max_length=64)),
                ("entrepot_origine_code", models.CharField(blank=True, max_length=16)),
                (
                    "emplacement_origine_code",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "entrepot_destination_code",
                    models.CharField(blank=True, max_length=16),
                ),
                (
                    "emplacement_destination_code",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("uom", models.CharField(blank=True, max_length=16)),
                (
                    "unit_cost_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "value_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("source_document", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock",
                        to="analytics.andimarticle",
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_stock",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_mouvement_stock",
                "indexes": [
                    models.Index(fields=["dim_temps"], name="an_fact_mou_dim_tem_aee635_idx"),
                    models.Index(fields=["move_type"], name="an_fact_mou_move_ty_1bcab3_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "source_move_id"),
                        name="uniq_an_fact_mouvement_stock",
                    )
                ],
            },
        ),
    ]
