# Generated by Django 5.2.17 on 2026-09-04 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_anwarehousestate_watermark_pur_receipt_line_and_more"),
        ("core", "0029_tenant_whatsapp_cost_alert_threshold_pct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anwarehousestate",
            name="watermark_mrp_order",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AnFactOrdreFabrication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_order_id", models.UUIDField()),
                ("order_reference", models.CharField(blank=True, max_length=64)),
                ("atelier_code", models.CharField(blank=True, max_length=32)),
                (
                    "qty_produced",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_scrapped",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "cout_reel_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "cout_planifie_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "ecart_cout_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordres_fabrication",
                        to="analytics.andimarticle",
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordres_fabrication",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_ordre_fabrication",
                "indexes": [
                    models.Index(fields=["dim_temps"], name="an_fact_ord_dim_tem_be9777_idx"),
                    models.Index(fields=["atelier_code"], name="an_fact_ord_atelier_64d20a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "source_order_id"),
                        name="uniq_an_fact_ordre_fabrication",
                    )
                ],
            },
        ),
    ]
