# Generated by Django 5.2.17 on 2026-09-05 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_anwarehousestate_watermark_mrp_order_and_more"),
        ("core", "0029_tenant_whatsapp_cost_alert_threshold_pct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anwarehousestate",
            name="watermark_pay_payslip",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AnFactPaie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_payslip_id", models.UUIDField()),
                ("employee_id", models.UUIDField()),
                ("period_code", models.CharField(blank=True, max_length=32)),
                ("payslip_reference", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=16)),
                (
                    "gross_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "taxable_base_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "irsa_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "social_employee_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "social_employer_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("payment_method", models.CharField(blank=True, max_length=16)),
                (
                    "regulatory_parameter_versions",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paies",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_paie",
                "indexes": [
                    models.Index(fields=["dim_temps"], name="an_fact_pai_dim_tem_6edac1_idx"),
                    models.Index(fields=["employee_id"], name="an_fact_pai_employe_ff2bfa_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "source_payslip_id"), name="uniq_an_fact_paie"
                    )
                ],
            },
        ),
    ]
