# Generated by Django 5.2.17 on 2026-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_anwarehousestate_watermark_pay_payslip_anfactpaie"),
    ]

    operations = [
        migrations.AddField(
            model_name="anmetricdefinition",
            name="fait_source",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
