# Generated by Django 5.2.17 on 2026-09-06 16:54

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_seed_metric_dictionary"),
        ("core", "0033_tenant_whatsapp_phone_number_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnFactEchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("source_exchange_id", models.UUIDField()),
                ("connecteur_code", models.CharField(blank=True, max_length=64)),
                ("connecteur_famille", models.CharField(blank=True, max_length=16)),
                ("liaison_nom", models.CharField(blank=True, max_length=150)),
                ("direction", models.CharField(blank=True, max_length=8)),
                ("operation", models.CharField(blank=True, max_length=32)),
                ("etat", models.CharField(blank=True, max_length=24)),
                ("code_resultat", models.CharField(blank=True, max_length=64)),
                ("tentatives", models.PositiveSmallIntegerField(default=0)),
                (
                    "duree_reglement_s",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("octets", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dim_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="echanges",
                        to="analytics.andimtemps",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "an_fact_echange",
                "indexes": [
                    models.Index(
                        fields=["dim_temps"], name="an_fact_ech_dim_tem_f72e0d_idx"
                    ),
                    models.Index(
                        fields=["connecteur_code"],
                        name="an_fact_ech_connect_492afb_idx",
                    ),
                    models.Index(fields=["etat"], name="an_fact_ech_etat_2557cc_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "source_exchange_id"),
                        name="uniq_an_fact_echange",
                    )
                ],
            },
        ),
    ]
