# Generated by Django 5.2.17 on 2026-08-28 04:31

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StkLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("variant_id", models.UUIDField()),
                ("name", models.CharField(max_length=64)),
                ("date_production", models.DateField(blank=True, null=True)),
                ("date_expiry", models.DateField(blank=True, null=True)),
                ("supplier_lot", models.CharField(blank=True, max_length=64)),
                ("origin", models.CharField(blank=True, max_length=255)),
                ("certificate_document_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_lot",
            },
        ),
        migrations.CreateModel(
            name="StkMove",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("variant_id", models.UUIDField()),
                ("qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("uom", models.CharField(blank=True, max_length=16)),
                ("date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("done", "Valide"),
                            ("cancelled", "Annule"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("reception", "Reception"),
                            ("livraison", "Livraison"),
                            ("transfert_interne", "Transfert interne"),
                            ("production_in", "Entree production"),
                            ("production_out", "Sortie production"),
                            ("retour", "Retour"),
                            ("rebut", "Rebut"),
                            ("ajustement", "Ajustement"),
                            ("sous_traitance", "Sous-traitance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_document", models.CharField(blank=True, max_length=255)),
                (
                    "unit_cost_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "value_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_out",
                        to="stocks.stklocation",
                    ),
                ),
                (
                    "location_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_in",
                        to="stocks.stklocation",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moves",
                        to="stocks.stklot",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by",
                        to="stocks.stkmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_move",
            },
        ),
        migrations.CreateModel(
            name="StkQuant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("variant_id", models.UUIDField()),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_reserved",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("uom", models.CharField(blank=True, max_length=16)),
                (
                    "unit_cost_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "value_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("last_count_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quants",
                        to="stocks.stklocation",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quants",
                        to="stocks.stklot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_quant",
            },
        ),
        migrations.CreateModel(
            name="StkValuationLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("variant_id", models.UUIDField()),
                ("qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("unit_cost_mga", models.DecimalField(decimal_places=4, max_digits=18)),
                ("value_mga", models.DecimalField(decimal_places=4, max_digits=18)),
                ("remaining_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "remaining_value_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_layers",
                        to="stocks.stkmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_valuation_layer",
            },
        ),
        migrations.AddConstraint(
            model_name="stklot",
            constraint=models.UniqueConstraint(
                fields=("tenant", "variant_id", "name"), name="uniq_stk_lot_variant_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="stkquant",
            constraint=models.UniqueConstraint(
                fields=("variant_id", "location", "lot"),
                name="uniq_stk_quant_variant_location_lot",
                nulls_distinct=False,
            ),
        ),
    ]
