# Generated by Django 5.2.17 on 2026-08-28 05:33

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("stocks", "0003_stk_move_from_ne_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StkMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("poids", "Poids"),
                            ("longueur", "Longueur"),
                            ("largeur", "Largeur"),
                            ("surface", "Surface"),
                            ("epaisseur", "Epaisseur"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("uom", models.CharField(blank=True, max_length=16)),
                ("device", models.CharField(blank=True, max_length=120)),
                ("measured_at", models.DateTimeField()),
                (
                    "variance_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("photo_document_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measurements",
                        to="stocks.stkmove",
                    ),
                ),
                (
                    "quant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measurements",
                        to="stocks.stkquant",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_measurement",
            },
        ),
        migrations.CreateModel(
            name="StkQualityState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("conforme", "Conforme"),
                            ("defaut_mineur", "Defaut mineur"),
                            ("defaut_majeur", "Defaut majeur"),
                            ("rebut", "Rebut"),
                            ("en_quarantaine", "En quarantaine"),
                            ("declasse", "Declasse"),
                        ],
                        default="conforme",
                        max_length=16,
                    ),
                ),
                (
                    "defect_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("description", models.TextField(blank=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defect_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_states",
                        to="stocks.stkdefecttype",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_states",
                        to="stocks.stklot",
                    ),
                ),
                (
                    "quant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_states",
                        to="stocks.stkquant",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_quality_state",
            },
        ),
    ]
