# Generated by Django 5.2.17 on 2026-08-28 05:56

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("stocks", "0004_stkmeasurement_stkqualitystate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StkPicking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entree", "Entree"),
                            ("sortie", "Sortie"),
                            ("interne", "Interne"),
                        ],
                        max_length=16,
                    ),
                ),
                ("partner_id", models.UUIDField(blank=True, null=True)),
                ("date_scheduled", models.DateField(blank=True, null=True)),
                ("date_done", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("waiting", "En attente"),
                            ("ready", "Pret"),
                            ("done", "Termine"),
                            ("cancelled", "Annule"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("source_document", models.CharField(blank=True, max_length=255)),
                ("carrier", models.CharField(blank=True, max_length=150)),
                ("tracking", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickings_out",
                        to="stocks.stklocation",
                    ),
                ),
                (
                    "location_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickings_in",
                        to="stocks.stklocation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_picking",
            },
        ),
        migrations.AddField(
            model_name="stkmove",
            name="picking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moves",
                to="stocks.stkpicking",
            ),
        ),
    ]
