# Generated by Django 5.2.17 on 2026-08-28 06:35

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("stocks", "0006_stkinventory_stkinventoryline_stkreservation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StkReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("partner_id", models.UUIDField()),
                ("source_document", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "quality_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conforme", "Conforme"),
                            ("defaut_mineur", "Defaut mineur"),
                            ("defaut_majeur", "Defaut majeur"),
                            ("rebut", "Rebut"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("avoir", "Avoir"),
                            ("remplacement", "Remplacement"),
                            ("reparation", "Reparation"),
                            ("refus", "Refus"),
                        ],
                        max_length=16,
                    ),
                ),
                ("variant_id", models.UUIDField()),
                ("qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("processed", "Traite"),
                            ("cancelled", "Annule"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="stocks.stkmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_return",
            },
        ),
    ]
