# Generated by Django 5.2.17 on 2026-08-28 13:00

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("stocks", "0008_stklot_barcode_stknegativestockexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StkImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("initial_quantities", "Quantités initiales")],
                        default="initial_quantities",
                        max_length=24,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("format_version", models.PositiveSmallIntegerField()),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("anomaly_rows_count", models.PositiveIntegerField(default=0)),
                ("applied_rows_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_import_batch",
            },
        ),
        migrations.CreateModel(
            name="StkImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Importée"),
                            ("anomaly", "Anomalie — à corriger"),
                            ("resolved", "Anomalie corrigée"),
                            ("discarded", "Écartée"),
                        ],
                        default="anomaly",
                        max_length=16,
                    ),
                ),
                ("anomaly_codes", models.JSONField(blank=True, default=list)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="stocks.stkimportbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stocks.stkmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stk_import_row",
            },
        ),
        migrations.AddIndex(
            model_name="stkimportbatch",
            index=models.Index(
                fields=["tenant", "kind"], name="stk_import__tenant__d47214_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stkimportrow",
            index=models.Index(
                fields=["batch", "status"], name="stk_import__batch_i_1a016a_idx"
            ),
        ),
    ]
