# Generated by Django 5.2.17 on 2026-08-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("stocks", "0009_stkimportbatch_stkimportrow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stkimportrow",
            name="qualification_approval_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="stkimportrow",
            name="resolved_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stocks.stklocation",
            ),
        ),
        migrations.AddField(
            model_name="stkimportrow",
            name="resolved_variant_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stkimportrow",
            name="uses_placeholder_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stkimportrow",
            name="uses_placeholder_variant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stkimportrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Importée"),
                    ("needs_qualification", "À qualifier"),
                    ("pending_approval", "Qualification en attente d'approbation"),
                    ("qualified", "Qualifiée"),
                    ("unresolvable", "Non résoluble — à corriger"),
                    ("resolved", "Anomalie corrigée"),
                    ("discarded", "Écartée"),
                ],
                default="unresolvable",
                max_length=24,
            ),
        ),
    ]
