# Generated by Django 5.2.17 on 2026-08-28 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0010_stkimportrow_qualification_approval_request_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stkimportrow",
            options={
                "permissions": [
                    (
                        "qualify_stkimportrow",
                        "Peut qualifier une ligne d'import de stock",
                    )
                ]
            },
        ),
    ]
