# Generated by Django 5.2.17 on 2026-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0013_stkrecall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stkmove",
            name="move_type",
            field=models.CharField(
                choices=[
                    ("reception", "Reception"),
                    ("livraison", "Livraison"),
                    ("transfert_interne", "Transfert interne"),
                    ("production_in", "Entree production"),
                    ("production_out", "Sortie production"),
                    ("retour", "Retour"),
                    ("rebut", "Rebut"),
                    ("ajustement", "Ajustement"),
                    ("sous_traitance", "Sous-traitance"),
                    ("vente_comptoir", "Vente au comptoir"),
                    ("sous_produit", "Sous-produit"),
                    ("casse", "Casse"),
                ],
                max_length=32,
            ),
        ),
    ]
