# Generated by Django 5.2.17 on 2026-09-04 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_tenant_whatsapp_cost_alert_threshold_pct_and_more"),
        ("stocks", "0015_move_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stkmove",
            name="client_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="stkmove",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_uuid__isnull", False)),
                fields=("tenant", "client_uuid"),
                name="uniq_stk_move_client_uuid_per_tenant",
            ),
        ),
    ]
