# Generated by Django 5.2.17 on 2026-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0017_move_immutability_client_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="stkinventory",
            name="is_blind",
            field=models.BooleanField(default=False),
        ),
    ]
