# Generated by Django 5.2.17 on 2026-09-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0018_inventory_blind_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stkinventory",
            name="is_blind",
            field=models.BooleanField(default=True),
        ),
    ]
