# Generated by Django 5.2.17 on 2026-08-30 05:23

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0020_alter_riskitem_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("assist", "Assistant contextuel"),
                            ("anomaly_narrative", "Narrative d'anomalie"),
                            ("search", "Recherche en langage naturel"),
                            ("insight", "Insight proactif"),
                            ("recommendation", "Recommandation d'action"),
                        ],
                        max_length=32,
                    ),
                ),
                ("prompt_tokens_estimate", models.PositiveIntegerField(default=0)),
                ("completion_tokens_estimate", models.PositiveIntegerField(default=0)),
                ("provider_backend", models.CharField(default="stub", max_length=32)),
                ("succeeded", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiUsageLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("monthly_token_budget", models.PositiveIntegerField(default=100000)),
                ("alert_threshold_pct", models.PositiveSmallIntegerField(default=80)),
                ("hard_stop", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_limit",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="uniq_ai_usage_limit_per_tenant"
                    )
                ],
            },
        ),
    ]
