# Generated by Django 5.2.17 on 2026-08-30 09:01

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_aiinsight"),
        ("core", "0020_alter_riskitem_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("context_module", models.CharField(max_length=64)),
                ("context_action", models.CharField(max_length=64)),
                ("role_code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
                (
                    "target_module",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "target_action_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_recommendation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["context_module", "context_action", "role_code"],
                        name="ai_recommen_context_443ec9_idx",
                    )
                ],
            },
        ),
    ]
