# Generated by Django 5.2.17 on 2026-08-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_aidataquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequest",
            name="feature",
            field=models.CharField(
                choices=[
                    ("assist", "Assistant contextuel"),
                    ("anomaly_narrative", "Narrative d'anomalie"),
                    ("search", "Recherche en langage naturel"),
                    ("insight", "Insight proactif"),
                    ("recommendation", "Recommandation d'action"),
                    ("data_query", "Question-donnees IA"),
                    ("helpdesk_reply", "Suggestion de reponse helpdesk"),
                ],
                max_length=32,
            ),
        ),
    ]
