# Generated by Django 5.2.17 on 2026-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_hd3_kb_and_response_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aianomaly",
            name="status",
            field=models.CharField(
                choices=[
                    ("ouverte", "Ouverte"),
                    ("traitee", "Traitée"),
                    ("ignoree", "Ignorée"),
                ],
                default="ouverte",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="airequest",
            name="feature",
            field=models.CharField(
                choices=[
                    ("assist", "Assistant contextuel"),
                    ("anomaly_narrative", "Narrative d'anomalie"),
                    ("search", "Recherche en langage naturel"),
                    ("insight", "Insight proactif"),
                    ("recommendation", "Recommandation d'action"),
                    ("data_query", "Question-donnees IA"),
                    ("helpdesk_reply", "Suggestion de réponse helpdesk"),
                ],
                max_length=32,
            ),
        ),
    ]
