# Generated by Django 5.2.17 on 2026-09-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_alter_aianomaly_status_alter_airequest_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidataquery",
            name="duration_ms",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
