# Generated by Django 5.2.17 on 2026-08-28 19:08

import apps.core.db.fields
import apps.core.db.uuid7
import django.db.models.deletion
import django_fsm
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("presence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrsAbsenceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conge_paye", "Congé payé"),
                            ("conge_sans_solde", "Congé sans solde"),
                            ("maladie", "Maladie"),
                            ("maternite", "Maternité"),
                            ("paternite", "Paternité"),
                            ("permission", "Permission"),
                            ("formation", "Formation"),
                            ("injustifie", "Injustifié"),
                            ("mission", "Mission"),
                            ("recuperation", "Récupération"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "pay_rate_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=5
                    ),
                ),
                ("requires_justification", models.BooleanField(default=False)),
                (
                    "max_days_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("deducts_from_balance", models.BooleanField(default=True)),
                ("approval_levels", models.PositiveSmallIntegerField(default=1)),
                ("advance_notice_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "justification_deadline_days",
                    models.PositiveSmallIntegerField(default=2),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prs_absence_type",
            },
        ),
        migrations.CreateModel(
            name="PrsAbsence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("half_day_start", models.BooleanField(default=False)),
                ("half_day_end", models.BooleanField(default=False)),
                (
                    "days_count",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "reason",
                    apps.core.db.fields.EncryptedCharField(blank=True, max_length=500),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumise"),
                            ("approved_l1", "Approuvée niveau 1"),
                            ("approved_l2", "Approuvée niveau 2"),
                            ("validated", "Validée"),
                            ("in_progress", "En cours"),
                            ("done", "Terminée"),
                            ("rejected", "Refusée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("justification_provided", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="presence.prsemployee",
                    ),
                ),
                (
                    "replacement_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="presence.prsemployee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absences",
                        to="presence.prsabsencetype",
                    ),
                ),
            ],
            options={
                "db_table": "prs_absence",
            },
        ),
        migrations.CreateModel(
            name="PrsLeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "acquired_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "taken_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "pending_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "carried_over_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("movements", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="presence.prsemployee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="presence.prsabsencetype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prs_leave_balance",
            },
        ),
        migrations.CreateModel(
            name="PrsOvertime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "rate_category",
                    models.CharField(
                        choices=[
                            ("h_sup_30", "Heures sup. 30%"),
                            ("h_sup_50", "Heures sup. 50%"),
                            ("nuit", "Nuit"),
                            ("dimanche", "Dimanche"),
                            ("ferie", "Jour férié"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[("draft", "Brouillon"), ("validated", "Validé")],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("payroll_period", models.CharField(blank=True, max_length=32)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtimes",
                        to="presence.prsemployee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prs_overtime",
            },
        ),
        migrations.AddConstraint(
            model_name="prsabsencetype",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_prs_absence_type_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="prsleavebalance",
            constraint=models.UniqueConstraint(
                fields=("employee", "year", "type"),
                name="uniq_prs_leave_balance_employee_year_type",
            ),
        ),
    ]
