# Generated by Django 5.2.17 on 2026-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feasibility", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feastudy",
            name="sector_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("textile", "Textile"),
                    ("cuir", "Cuir et maroquinerie"),
                    ("agroalimentaire", "Agroalimentaire"),
                    ("import_export", "Import-export généraliste"),
                    ("artisanat", "Artisanat"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="feastudy",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("completed", "Terminée"),
                    ("archived", "Archivée"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
