# Generated by Django 5.2.17 on 2026-08-26 20:53

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("core", "0015_tenant_fiscal_regime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccMove",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("date", models.DateField()),
                ("partner_id", models.UUIDField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("posted", "Publiee"),
                            ("cancelled", "Annulee"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("entry", "Ecriture diverse"),
                            ("customer_invoice", "Facture client"),
                            ("customer_credit_note", "Avoir client"),
                            ("supplier_invoice", "Facture fournisseur"),
                            ("supplier_credit_note", "Avoir fournisseur"),
                        ],
                        default="entry",
                        max_length=24,
                    ),
                ),
                ("narration", models.TextField(blank=True)),
                ("currency", models.CharField(default="MGA", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1, max_digits=18),
                ),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="accounting.accjournal",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="accounting.accperiod",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by_set",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_move",
            },
        ),
        migrations.CreateModel(
            name="AccMoveLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.UUIDField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "debit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_currency",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("currency", models.CharField(default="MGA", max_length=3)),
                (
                    "tax_base",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("analytic_distribution", models.JSONField(blank=True, default=dict)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "matching_number",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "reconciled_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accmoveline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_move_line",
            },
        ),
        migrations.AddIndex(
            model_name="accmove",
            index=models.Index(
                fields=["journal", "period", "state"],
                name="acc_move_journal_cf10db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accmoveline",
            index=models.Index(
                fields=["account"], name="acc_move_li_account_171149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accmoveline",
            index=models.Index(
                fields=["matching_number"], name="acc_move_li_matchin_07c9ff_idx"
            ),
        ),
    ]
