# Generated by Django 5.2.17 on 2026-08-26 21:08

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_move_immutability_field_aware"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accmove",
            options={
                "permissions": [
                    ("validate_accmove", "Peut valider une ecriture/facture"),
                    ("cancel_accmove", "Peut annuler une facture avant paiement"),
                ]
            },
        ),
        migrations.AddField(
            model_name="accmove",
            name="invoice_state",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Brouillon"),
                    ("to_validate", "A valider"),
                    ("validated", "Validee"),
                    ("paid_partially", "Payee partiellement"),
                    ("paid", "Payee"),
                    ("cancelled", "Annulee"),
                    ("overdue", "En retard"),
                    ("in_dispute", "En contentieux"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
