# Generated by Django 5.2.17 on 2026-08-27 15:49

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0008_accanalyticplan_accanalyticaccount_accanalyticline_and_more",
        ),
        ("core", "0016_tenant_vat_opted_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccTaxCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "declaration_type",
                    models.CharField(
                        choices=[
                            ("irsa", "IRSA"),
                            ("tva", "TVA"),
                            ("ir_acompte", "Acompte IR"),
                            ("is_annual", "IS annuel"),
                            ("ir_annual", "IR annuel"),
                            ("ircm", "IRCM"),
                            ("dcom", "DCOM"),
                            ("tvm", "TVM"),
                            ("ift", "IFT"),
                            ("ifpb", "IFPB"),
                            ("etats_financiers", "Depot des etats financiers"),
                        ],
                        max_length=24,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuelle"),
                            ("bimonthly", "Bimestrielle"),
                            ("semiannual", "Semestrielle"),
                            ("annual", "Annuelle"),
                            ("variable", "Variable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_recurring_template", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_tax_calendar",
                "indexes": [
                    models.Index(
                        fields=["due_date"], name="acc_tax_cal_due_dat_5aabd5_idx"
                    )
                ],
            },
        ),
    ]
