# Generated by Django 5.2.17 on 2026-08-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_acctaxcalendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="accaccount",
            name="functional_destination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("production", "Production"),
                    ("distribution", "Distribution"),
                    ("administration", "Administration"),
                    ("autre", "Autre"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accaccount",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
    ]
