# Generated by Django 5.2.17 on 2026-08-27 16:25

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accaccount_functional_destination_and_more"),
        ("core", "0016_tenant_vat_opted_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("incorporelle", "Immobilisation incorporelle"),
                            ("corporelle", "Immobilisation corporelle"),
                            ("financiere", "Immobilisation financiere"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("acquisition_date", models.DateField()),
                (
                    "acquisition_value_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[("lineaire", "Lineaire"), ("degressif", "Degressif")],
                        max_length=16,
                    ),
                ),
                ("useful_life_years", models.PositiveIntegerField()),
                (
                    "residual_value_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "disposal_value_mga",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "En service"),
                            ("disposed", "Cedee/mise au rebut"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_asset",
            },
        ),
        migrations.CreateModel(
            name="AccAssetDepreciation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_accumulated_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "annual_dotation_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "closing_accumulated_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_entries",
                        to="accounting.accasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accfiscalyear",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_asset_depreciation",
            },
        ),
        migrations.CreateModel(
            name="AccProvision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("nature", models.CharField(max_length=200)),
                (
                    "opening_amount_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "dotation_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "reprise_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "closing_amount_mga",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accfiscalyear",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_provision",
            },
        ),
        migrations.CreateModel(
            name="AccAssetMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("acquisition", "Acquisition"),
                            ("disposal", "Cession/mise au rebut"),
                            ("transfer", "Virement de poste a poste"),
                        ],
                        max_length=16,
                    ),
                ),
                ("date", models.DateField()),
                ("amount_mga", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="accounting.accasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_asset_movement",
                "indexes": [
                    models.Index(
                        fields=["asset", "date"], name="acc_asset_m_asset_i_20b860_idx"
                    )
                ],
            },
        ),
    ]
