# Generated by Django 5.2.17 on 2026-08-28 11:58

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_acclandedcostbatch_acclandedcostcomponent_and_more"),
        ("core", "0016_tenant_vat_opted_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash_journal", "Journal de caisse"),
                            ("chart_of_accounts", "Plan comptable"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("format_version", models.PositiveSmallIntegerField()),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("anomaly_rows_count", models.PositiveIntegerField(default=0)),
                ("applied_rows_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accjournal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_import_batch",
            },
        ),
        migrations.CreateModel(
            name="AccImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Importee"),
                            ("anomaly", "Anomalie — a corriger"),
                            ("resolved", "Anomalie corrigee"),
                            ("discarded", "Ecartee"),
                        ],
                        default="anomaly",
                        max_length=16,
                    ),
                ),
                ("anomaly_codes", models.JSONField(blank=True, default=list)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="accounting.accimportbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "resolved_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_import_row",
            },
        ),
        migrations.CreateModel(
            name="AccCashCategoryMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("category_label", models.CharField(max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_cash_category_mapping",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "category_label"),
                        name="uniq_cash_category_mapping",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="accimportbatch",
            index=models.Index(
                fields=["tenant", "kind"], name="acc_import__tenant__4fdfdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accimportrow",
            index=models.Index(
                fields=["batch", "status"], name="acc_import__batch_i_7e693e_idx"
            ),
        ),
    ]
