# Generated by Django 5.2.17 on 2026-08-28 16:32

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0019_accimportrow_partner_id_and_more"),
        ("core", "0016_tenant_vat_opted_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccInvoiceImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "customer_supplier_invoices",
                                "Factures client/fournisseur",
                            )
                        ],
                        default="customer_supplier_invoices",
                        max_length=32,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("format_version", models.PositiveSmallIntegerField()),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("anomaly_rows_count", models.PositiveIntegerField(default=0)),
                ("applied_rows_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_invoice_import_batch",
            },
        ),
        migrations.CreateModel(
            name="AccInvoiceImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                ("invoice_reference", models.CharField(blank=True, max_length=64)),
                (
                    "sens",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client", "Facture client"),
                            ("fournisseur", "Facture fournisseur"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Importée"),
                            ("needs_qualification", "À qualifier"),
                            (
                                "pending_approval",
                                "Qualification en attente d'approbation",
                            ),
                            ("qualified", "Qualifiée"),
                            ("unresolvable", "Non résoluble — à corriger"),
                            ("discarded", "Écartée"),
                        ],
                        default="unresolvable",
                        max_length=24,
                    ),
                ),
                ("anomaly_codes", models.JSONField(blank=True, default=list)),
                ("partner_id", models.UUIDField(blank=True, null=True)),
                ("resolved_variant_id", models.UUIDField(blank=True, null=True)),
                ("uses_placeholder_partner", models.BooleanField(default=False)),
                ("uses_placeholder_variant", models.BooleanField(default=False)),
                ("uses_placeholder_account", models.BooleanField(default=False)),
                ("uses_placeholder_tax", models.BooleanField(default=False)),
                ("uses_default_date", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="accounting.accinvoiceimportbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "qualification_approval_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "resolved_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "resolved_tax_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_invoice_import_row",
            },
        ),
        migrations.AddIndex(
            model_name="accinvoiceimportbatch",
            index=models.Index(fields=["tenant", "kind"], name="acc_invoice_tenant__f7bbf4_idx"),
        ),
        migrations.AddIndex(
            model_name="accinvoiceimportrow",
            index=models.Index(fields=["batch", "status"], name="acc_invoice_batch_i_bb32ac_idx"),
        ),
    ]
