# Generated by Django 5.2.17 on 2026-08-28 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0020_accinvoiceimportbatch_accinvoiceimportrow_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accimportrow",
            options={
                "permissions": [
                    (
                        "qualify_accimportrow",
                        "Peut qualifier une ligne d'import journal de caisse",
                    )
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="accinvoiceimportrow",
            options={
                "permissions": [
                    (
                        "qualify_accinvoiceimportrow",
                        "Peut qualifier une ligne d'import de facture",
                    )
                ]
            },
        ),
    ]
