# Generated by Django 5.2.17 on 2026-09-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_alter_accimportrow_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accaccount",
            name="sector_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("textile", "Textile"),
                    ("cuir", "Cuir et maroquinerie"),
                    ("agroalimentaire", "Agroalimentaire"),
                    ("import_export", "Import-export généraliste"),
                    ("artisanat", "Artisanat"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
