# Generated by Django 5.2.17 on 2026-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_accpartnerroleaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="accmove",
            name="received_by_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
