# Generated by Django 5.2.17 on 2026-09-05 06:09

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0024_accmove_received_by_ids"),
        ("core", "0029_tenant_whatsapp_cost_alert_threshold_pct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccAccountMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_code", models.CharField(max_length=20)),
                ("target_code", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "acc_account_mapping",
                "ordering": ["source_framework__code", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="AccChartOfAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=200)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("is_default_for_country", models.BooleanField(default=False)),
                ("fixture_name", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "db_table": "acc_chart_of_accounts",
                "ordering": ["framework__code", "country_code"],
            },
        ),
        migrations.CreateModel(
            name="AccFramework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PCG2005", "PCG 2005 (Madagascar)"),
                            ("SYSCOHADA_REVISE", "SYSCOHADA revise (zone OHADA)"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("default_country_code", models.CharField(max_length=2)),
                ("norm_version", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("validation_reserve", models.TextField(blank=True)),
                ("account_classes", models.JSONField(blank=True, default=dict)),
                ("class_classification", models.JSONField(blank=True, default=dict)),
                (
                    "financial_income_prefixes",
                    models.JSONField(blank=True, default=list),
                ),
                ("suspense_account_code", models.CharField(blank=True, max_length=20)),
                (
                    "suspense_account_class",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("bank_account_prefix", models.CharField(blank=True, max_length=20)),
                ("cash_account_prefix", models.CharField(blank=True, max_length=20)),
                (
                    "expense_class",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "income_class",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "investing_class",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "acc_framework",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccTenantDefaultAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("vente", "Produit des ventes"),
                            ("achat", "Charge des achats"),
                            ("tva", "TVA"),
                            ("client", "Client"),
                            ("fournisseur", "Fournisseur"),
                            ("banque", "Banque"),
                            ("caisse", "Caisse"),
                            ("stock", "Stock"),
                            ("variation_stock", "Variation de stock"),
                            ("ecart_caisse", "Ecart de caisse"),
                            ("charge_personnel", "Charge de personnel"),
                            ("dette_personnel", "Dette envers le personnel"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "acc_tenant_default_account",
                "ordering": ["role"],
            },
        ),
        migrations.AlterField(
            model_name="accaccount",
            name="account_class",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name="accaccount",
            name="chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="accounting.accchartofaccounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="accaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="acc_account_unique_tenant_code"
            ),
        ),
        migrations.AddField(
            model_name="accchartofaccounts",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charts",
                to="accounting.accframework",
            ),
        ),
        migrations.AddField(
            model_name="accaccountmapping",
            name="source_framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mappings_as_source",
                to="accounting.accframework",
            ),
        ),
        migrations.AddField(
            model_name="accaccountmapping",
            name="target_framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mappings_as_target",
                to="accounting.accframework",
            ),
        ),
        migrations.AddField(
            model_name="acctenantdefaultaccount",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.accaccount",
            ),
        ),
        migrations.AddField(
            model_name="acctenantdefaultaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="acctenantdefaultaccount",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="acctenantdefaultaccount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="accchartofaccounts",
            constraint=models.UniqueConstraint(
                fields=("framework", "country_code"),
                name="acc_chart_unique_framework_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="accaccountmapping",
            constraint=models.UniqueConstraint(
                fields=("source_framework", "source_code", "target_framework"),
                name="acc_account_mapping_unique_source_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="acctenantdefaultaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "role"), name="acc_default_account_unique_tenant_role"
            ),
        ),
    ]
