# Generated by Django 5.2.17 on 2026-09-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0026_seed_pcg2005_framework"),
    ]

    operations = [
        migrations.AddField(
            model_name="accframework",
            name="statement_structure",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
