"""ACC-6 — la declaration de TVA d'une periode entre enfin dans le modele.

Le critere : « La declaration de TVA d'une periode se rapproche a l'ariary
pres de la somme des ecritures de TVA de la periode, avec un etat
justificatif ligne a ligne. »

**Il n'y avait rien a rapprocher.** Le depot l'ecrivait lui-meme dans
`services/fiscal_export.py`, a la ligne ACC-TVA de son registre : « Aucune
declaration TVA dediee (pas de modele `acc_vat_declaration` a ce stade) :
approche via `trial_balance`/`general_ledger` filtres sur les comptes de
TVA collectee/deductible ». La liasse ANNUELLE (IS/IR) existait ; la
declaration PERIODIQUE, non.

**Deux tables et pas une**, parce que le critere demande deux choses de
nature differente : la declaration porte les totaux et l'ecart de
rapprochement, ses lignes portent l'etat justificatif par taxe. Le detail
ecriture par ecriture, lui, n'est PAS stocke : les lignes publiees sont
immuables par declencheur de base (`acc_move_immutable_when_posted`), donc
l'etat se recalcule a l'identique. Le figer dupliquerait une donnee deja
inalterable et creerait deux verites a faire diverger.

**Contrainte d'unicite par periode** : deux declarations pour la meme
periode rendraient « la » declaration ambigue, et la RLS ne suffirait pas
a trancher — c'est une regle metier, pas une regle d'isolation.

**Les montants sont conserves, ecart compris.** Une ecriture manuelle sur
un compte de TVA sans taxe designee est legale et creuse un ecart ; le
figer est ce qui permet de le retrouver. Le recalculer a chaque affichage
transformerait un ecart tracable en surprise.
"""

# Generated by Django 5.2.17 on 2026-09-08 11:16

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0033_closed_fiscal_year_write_lock"),
        ("core", "0040_remove_country_defaults_holidays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccVatDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "collected_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "deductible_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "net_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "collected_books_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "deductible_books_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "ecart_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("filed", "Deposee")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accperiod",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_vat_declaration",
                "ordering": ["-period__date_start"],
            },
        ),
        migrations.CreateModel(
            name="AccVatDeclarationLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sens",
                    models.CharField(
                        choices=[
                            ("collected", "TVA collectee"),
                            ("deductible", "TVA deductible"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "base_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "tax_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "books_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("move_line_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.accvatdeclaration",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.acctax",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_vat_declaration_line",
                "ordering": ["sens", "tax__code"],
            },
        ),
        migrations.AddConstraint(
            model_name="accvatdeclaration",
            constraint=models.UniqueConstraint(
                fields=("tenant", "period"), name="uniq_acc_vat_declaration_per_period"
            ),
        ),
    ]
