"""T4 (bloc C, EFA-6 et EFA-4) — le TROISIEME axe d'etat de la piece.

**Le piege que le cahier nomme en premier** (l.431) : « une facture peut
etre encaissee avant d'avoir obtenu son verdict, et un verdict peut
arriver apres l'encaissement, sans incoherence de statut ni blocage
comptable ; le modele ne doit donc pas les sequencer ».

Les deux axes existants ne pouvaient ni l'un ni l'autre porter cet etat.
`state` regit l'immuabilite comptable (brouillon / publiee / annulee).
`invoice_state` MELE DEJA validation et reglement — `validated`, `paid`,
`overdue`, `in_dispute`. Y loger le sort fiscal aurait force un ordre
entre « payee » et « acceptee par l'administration », soit exactement ce
que le critere interdit.

**Aucun changement pour l'existant.** `fiscal_state` vaut « hors du champ »
par defaut, et ce n'est pas un « pas encore » : la majorite des pieces —
ecritures diverses, factures fournisseur, tenant dans un pays sans profil
declare — ne sont jamais soumises. Toutes les lignes deja en base restent
donc exactement ou elles sont, sans migration de donnees.

**Le trigger d'immuabilite n'a pas a changer, et c'est verifie.** La
fonction `acc_move_reject_mutation_if_posted` (migration 0005) enumere les
colonnes COMPTABLES qu'une piece publiee ne peut plus voir bouger — c'est
une liste negative. Les cinq colonnes ajoutees ici n'y figurent pas, donc
un verdict fiscal peut s'inscrire sur une facture publiee, ce qui est la
condition meme d'EFA-6. Un test le prouve plutot que de le supposer
(`test_t4_efa6_orthogonal_states.py`).

**`fiscal_verdict_raw` et `fiscal_state` disent deux choses differentes**
(EFA-4) : « le verdict recu est conserve dans sa forme d'origine, EN PLUS
de son interpretation ». Une interpretation est revisable, un verdict recu
ne l'est pas — et le jour d'un desaccord avec l'administration, c'est la
forme d'origine qui fait foi.
"""

# Generated by Django 5.2.17 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0034_accvatdeclaration_accvatdeclarationline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accmove",
            name="fiscal_marking",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accmove",
            name="fiscal_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="accmove",
            name="fiscal_settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accmove",
            name="fiscal_state",
            field=models.CharField(
                choices=[
                    ("non_concerne", "Hors du champ de la facturation électronique"),
                    ("a_soumettre", "À soumettre"),
                    ("attente_verdict", "En attente de validation fiscale"),
                    ("accepte", "Acceptée par l'administration"),
                    ("rejete", "Rejetée par l'administration"),
                ],
                default="non_concerne",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="accmove",
            name="fiscal_verdict_raw",
            field=models.TextField(blank=True),
        ),
    ]
