"""T5 (bloc D, PAY-1 a PAY-4) — l'intention de reglement et la notification.

**L'intention n'est pas un encaissement.** C'est une demande adressee au
payeur, avec un lien et un code transmissibles. Tant qu'aucune notification
n'est revenue, aucune ecriture n'existe — l'interdit du §4.4, que PAY-3
redit : « un paiement recu sans correspondance ne produit aucune ecriture
tant qu'il n'est pas affecte ».

**`provider_code` sur l'intention, et pas seulement sur le tenant.** PAY-1
exige que le basculement agregateur/raccordement direct se fasse « sans
reprise des intentions en cours ». Une intention emise hier par
l'agregateur reste donc servie par lui, meme si le parametre a change ce
matin. Lire la voie sur le tenant a chaque fois aurait orpheline toutes les
intentions en vol au moment du basculement — exactement ce que le critere
interdit.

**La contrainte d'unicite sur `external_reference` sert PAY-7.** « Aucun
double debit n'est possible » : deux intentions ne peuvent pas revendiquer
la meme reference chez le tiers, sans quoi une notification ne saurait pas
laquelle regler et un rejeu en creerait une seconde en silence. La
condition exclut la chaine vide, qui signifie « le tiers n'a pas encore
attribue de reference » et vaut pour autant d'intentions qu'on veut.

**`raw` a cote de `state` sur la notification.** Meme discipline que
`AccMove.fiscal_verdict_raw` au lot T4 : `state` est notre lecture, `raw`
est ce que le tiers a envoye. Le jour d'un litige sur un encaissement,
c'est la forme d'origine qui fait foi, et une interpretation revisee ne
doit pas l'avoir ecrasee.

**Aucune migration de donnees.** Les deux tables sont neuves ; rien
d'existant n'est touche.
"""

# Generated by Django 5.2.17 on 2026-09-09 00:53

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0035_t4_accmove_fiscal_state"),
        ("core", "0041_tenant_stat_alter_tenant_nif"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccPaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("document_type", models.CharField(max_length=64)),
                ("document_id", models.UUIDField()),
                ("provider_code", models.CharField(max_length=32)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="MGA", max_length=3)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("creee", "Creee"),
                            ("transmise", "Transmise au payeur"),
                            ("reglee", "Reglee"),
                            ("expiree", "Expiree"),
                            ("annulee", "Annulee"),
                        ],
                        default="creee",
                        max_length=16,
                    ),
                ),
                ("payment_link", models.URLField(blank=True)),
                ("payment_code", models.CharField(blank=True, max_length=64)),
                (
                    "external_reference",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_payment_intent",
            },
        ),
        migrations.CreateModel(
            name="AccPaymentNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("provider_code", models.CharField(max_length=32)),
                ("external_reference", models.CharField(db_index=True, max_length=128)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="MGA", max_length=3)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("rapprochee", "Rapprochee"),
                            ("orpheline", "En attente de rapprochement"),
                            ("doublon", "Doublon"),
                            ("refusee", "Refusee"),
                        ],
                        default="orpheline",
                        max_length=16,
                    ),
                ),
                ("raw", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="accounting.accpaymentintent",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="accounting.accpayment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_payment_notification",
            },
        ),
        migrations.AddIndex(
            model_name="accpaymentintent",
            index=models.Index(
                fields=["document_type", "document_id"],
                name="acc_payment_documen_98ee54_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accpaymentintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_reference", ""), _negated=True),
                fields=("tenant", "external_reference"),
                name="uniq_acc_payment_intent_external_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="accpaymentnotification",
            index=models.Index(
                fields=["state", "received_at"], name="acc_payment_state_34b498_idx"
            ),
        ),
    ]
