# Generated by Django 5.2.17 on 2026-09-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0036_t5_payment_intent_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acctenantdefaultaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("vente", "Produit des ventes"),
                    ("achat", "Charge des achats"),
                    ("tva", "TVA"),
                    ("client", "Client"),
                    ("fournisseur", "Fournisseur"),
                    ("banque", "Banque"),
                    ("caisse", "Caisse"),
                    ("stock", "Stock"),
                    ("variation_stock", "Variation de stock"),
                    ("ecart_caisse", "Ecart de caisse"),
                    ("charge_personnel", "Charge de personnel"),
                    ("dette_personnel", "Dette envers le personnel"),
                    ("commission_encaissement", "Commission d'encaissement"),
                ],
                max_length=32,
            ),
        ),
    ]
