# Generated by Django 5.2.17 on 2026-09-09 06:22

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0037_t5_payment_fee_account_role"),
        ("core", "0042_t5_tenant_mobile_payment_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="acctenantdefaultaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("vente", "Produit des ventes"),
                    ("achat", "Charge des achats"),
                    ("tva", "TVA"),
                    ("client", "Client"),
                    ("fournisseur", "Fournisseur"),
                    ("banque", "Banque"),
                    ("caisse", "Caisse"),
                    ("stock", "Stock"),
                    ("variation_stock", "Variation de stock"),
                    ("ecart_caisse", "Ecart de caisse"),
                    ("charge_personnel", "Charge de personnel"),
                    ("dette_personnel", "Dette envers le personnel"),
                    ("commission_encaissement", "Commission d'encaissement"),
                    ("passage_encaissement", "Compte de passage d'encaissement"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AccAggregatorPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("provider_code", models.CharField(max_length=32)),
                ("external_reference", models.CharField(db_index=True, max_length=128)),
                ("payout_date", models.DateField()),
                ("gross_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("net_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="MGA", max_length=3)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("annonce", "Annonce par l'agregateur"),
                            ("regle", "Rapproche et comptabilise"),
                            ("conteste", "Conteste"),
                        ],
                        default="annonce",
                        max_length=16,
                    ),
                ),
                (
                    "matching_number",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aggregator_payouts",
                        to="accounting.accmove",
                    ),
                ),
                (
                    "statement_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aggregator_payouts",
                        to="accounting.accbankstatementline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_aggregator_payout",
            },
        ),
        migrations.AddField(
            model_name="accpaymentnotification",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="accounting.accaggregatorpayout",
            ),
        ),
        migrations.AddIndex(
            model_name="accaggregatorpayout",
            index=models.Index(
                fields=["state", "payout_date"], name="acc_aggrega_state_8507e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accaggregatorpayout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_reference", ""), _negated=True),
                fields=("tenant", "external_reference"),
                name="uniq_acc_aggregator_payout_external_reference",
            ),
        ),
    ]
