# Generated by Django 5.2.17 on 2026-09-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0038_t5_aggregator_payout"),
    ]

    operations = [
        migrations.AddField(
            model_name="accbankstatementline",
            name="import_fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="accbankstatementline",
            name="match_confidence",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accbankstatementline",
            name="matched_by_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions",
                to="accounting.accreconcilerule",
            ),
        ),
        migrations.AddField(
            model_name="accbankstatementline",
            name="suggested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
