# Generated by Django 5.2.17 on 2026-09-09 09:03

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0039_t6_statement_report"),
        ("core", "0042_t5_tenant_mobile_payment_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccTransferOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("paie", "Paie"),
                            ("achats", "Achats"),
                            ("saisie", "Saisie manuelle"),
                        ],
                        default="saisie",
                        max_length=16,
                    ),
                ),
                ("execution_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("currency", models.CharField(default="MGA", max_length=3)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("exporte", "Exporte"),
                            ("remis", "Remis a la banque"),
                            ("rapproche", "Rapproche du debit"),
                        ],
                        default="brouillon",
                        max_length=16,
                    ),
                ),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("remitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.accaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statement_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_orders",
                        to="accounting.accbankstatementline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_transfer_order",
            },
        ),
        migrations.CreateModel(
            name="AccTransferOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("document_type", models.CharField(max_length=64)),
                ("document_id", models.UUIDField()),
                ("beneficiary_label", models.CharField(max_length=150)),
                ("beneficiary_account", models.CharField(blank=True, max_length=64)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("reference", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.acctransferorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acc_transfer_order_line",
            },
        ),
        migrations.AddIndex(
            model_name="acctransferorder",
            index=models.Index(
                fields=["state", "execution_date"], name="acc_transfe_state_8b090c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acctransferorderline",
            index=models.Index(
                fields=["document_type", "document_id"],
                name="acc_transfe_documen_298eaf_idx",
            ),
        ),
    ]
