# Generated by Django 5.2.17 on 2026-09-11 18:03

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0040_t6_transfer_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accaccount",
            name="type",
            field=models.CharField(
                choices=[
                    ("asset", "Actif"),
                    ("liability", "Passif"),
                    ("equity", "Capitaux propres"),
                    ("income", "Produit"),
                    ("expense", "Charge"),
                    ("receivable", "Créance"),
                    ("payable", "Dette"),
                    ("bank", "Banque"),
                    ("cash", "Caisse"),
                    ("tax", "Taxe"),
                    ("stock", "Stock"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accaggregatorpayout",
            name="provider_code",
            field=models.CharField(
                choices=[
                    ("agregateur", "Agrégateur (versement groupé)"),
                    (
                        "raccordement_direct",
                        "Raccordement direct (versement à l'unité)",
                    ),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="accaggregatorpayout",
            name="state",
            field=models.CharField(
                choices=[
                    ("annonce", "Annoncé par l'agrégateur"),
                    ("regle", "Rapproché et comptabilisé"),
                    ("conteste", "Contesté"),
                ],
                default="annonce",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("incorporelle", "Immobilisation incorporelle"),
                    ("corporelle", "Immobilisation corporelle"),
                    ("financiere", "Immobilisation financière"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accasset",
            name="depreciation_method",
            field=models.CharField(
                choices=[("lineaire", "Linéaire"), ("degressif", "Dégressif")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accasset",
            name="state",
            field=models.CharField(
                choices=[("active", "En service"), ("disposed", "Cédée/mise au rebut")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accassetmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("acquisition", "Acquisition"),
                    ("disposal", "Cession/mise au rebut"),
                    ("transfer", "Virement de poste à poste"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accbankstatementline",
            name="state",
            field=models.CharField(
                choices=[
                    ("unmatched", "Non rapproché"),
                    ("rule_suggested", "Suggéré par une règle"),
                    ("matched", "Rapproché"),
                ],
                default="unmatched",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accbudget",
            name="state",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("approved", "Approuvé")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accfiscalyear",
            name="state",
            field=models.CharField(
                choices=[
                    ("open", "Ouvert"),
                    ("closing", "En clôture"),
                    ("closed", "Clôturé"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accframework",
            name="code",
            field=models.CharField(
                choices=[
                    ("PCG2005", "PCG 2005 (Madagascar)"),
                    ("SYSCOHADA_REVISE", "SYSCOHADA révisé (zone OHADA)"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="accimportrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Importée"),
                    ("needs_qualification", "À qualifier"),
                    ("pending_approval", "Qualification en attente d'approbation"),
                    ("qualified", "Qualifiée"),
                    ("unresolvable", "Non résoluble — à corriger"),
                    ("resolved", "Anomalie corrigée"),
                    ("discarded", "Écartée"),
                ],
                default="unresolvable",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="accircmdeclaration",
            name="state",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("filed", "Déposée")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accjournal",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Ventes"),
                    ("purchase", "Achats"),
                    ("bank", "Banque"),
                    ("cash", "Caisse"),
                    ("misc", "Opérations diverses"),
                    ("payroll", "Paie"),
                    ("stock", "Stock"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="acclandedcostbatch",
            name="allocation_method",
            field=models.CharField(
                choices=[
                    ("by_value", "Par valeur"),
                    ("by_weight", "Par poids"),
                    ("by_quantity", "Par quantité"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="acclandedcostbatch",
            name="state",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("finalized", "Finalisé")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="acclocaltax",
            name="state",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("filed", "Déposée")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="acclocaltax",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("ift", "IFT — Impôt foncier sur les terrains"),
                    ("ifpb", "IFPB — Impôt foncier sur la propriété bâtie"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accmobilemoneystatementline",
            name="state",
            field=models.CharField(
                choices=[("unmatched", "Non rapproché"), ("matched", "Rapproché")],
                default="unmatched",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accmove",
            name="invoice_state",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Brouillon"),
                    ("to_validate", "A valider"),
                    ("validated", "Validée"),
                    ("paid_partially", "Payée partiellement"),
                    ("paid", "Payée"),
                    ("cancelled", "Annulée"),
                    ("overdue", "En retard"),
                    ("in_dispute", "En contentieux"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="accmove",
            name="move_type",
            field=models.CharField(
                choices=[
                    ("entry", "Écriture diverse"),
                    ("customer_invoice", "Facture client"),
                    ("customer_credit_note", "Avoir client"),
                    ("supplier_invoice", "Facture fournisseur"),
                    ("supplier_credit_note", "Avoir fournisseur"),
                ],
                default="entry",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="accmove",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("posted", "Publiée"),
                    ("cancelled", "Annulée"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accpayment",
            name="direction",
            field=models.CharField(
                choices=[("inbound", "Encaissement"), ("outbound", "Décaissement")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("especes", "Espèces"),
                    ("virement", "Virement"),
                    ("cheque", "Chèque"),
                    ("mobile_money", "Mobile money"),
                    ("traite", "Traite"),
                    ("compensation", "Compensation"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accpayment",
            name="state",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("posted", "Publié")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accpaymentintent",
            name="provider_code",
            field=models.CharField(
                choices=[
                    ("agregateur", "Agrégateur (versement groupé)"),
                    (
                        "raccordement_direct",
                        "Raccordement direct (versement à l'unité)",
                    ),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="accpaymentintent",
            name="state",
            field=models.CharField(
                choices=[
                    ("creee", "Créée"),
                    ("transmise", "Transmise au payeur"),
                    ("reglee", "Réglée"),
                    ("expiree", "Expirée"),
                    ("annulee", "Annulée"),
                ],
                default="creee",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accpaymentnotification",
            name="provider_code",
            field=models.CharField(
                choices=[
                    ("agregateur", "Agrégateur (versement groupé)"),
                    (
                        "raccordement_direct",
                        "Raccordement direct (versement à l'unité)",
                    ),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="accpaymentnotification",
            name="state",
            field=models.CharField(
                choices=[
                    ("rapprochee", "Rapprochée"),
                    ("orpheline", "En attente de rapprochement"),
                    ("doublon", "Doublon"),
                    ("refusee", "Refusée"),
                ],
                default="orpheline",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="acctaxcalendar",
            name="declaration_type",
            field=models.CharField(
                choices=[
                    ("irsa", "IRSA"),
                    ("tva", "TVA"),
                    ("ir_acompte", "Acompte IR"),
                    ("is_annual", "IS annuel"),
                    ("ir_annual", "IR annuel"),
                    ("ircm", "IRCM"),
                    ("dcom", "DCOM"),
                    ("tvm", "TVM"),
                    ("ift", "IFT"),
                    ("ifpb", "IFPB"),
                    ("etats_financiers", "Dépôt des états financiers"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="acctenantdefaultaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("vente", "Produit des ventes"),
                    ("achat", "Charge des achats"),
                    ("tva", "TVA"),
                    ("client", "Client"),
                    ("fournisseur", "Fournisseur"),
                    ("banque", "Banque"),
                    ("caisse", "Caisse"),
                    ("stock", "Stock"),
                    ("variation_stock", "Variation de stock"),
                    ("ecart_caisse", "Écart de caisse"),
                    ("charge_personnel", "Charge de personnel"),
                    ("dette_personnel", "Dette envers le personnel"),
                    ("commission_encaissement", "Commission d'encaissement"),
                    ("passage_encaissement", "Compte de passage d'encaissement"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="acctransferorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("exporte", "Exporté"),
                    ("remis", "Remis à la banque"),
                    ("rapproche", "Rapproché du débit"),
                ],
                default="brouillon",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accvatdeclaration",
            name="state",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("filed", "Déposée")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="accvatdeclarationline",
            name="sens",
            field=models.CharField(
                choices=[
                    ("collected", "TVA collectée"),
                    ("deductible", "TVA déductible"),
                ],
                max_length=16,
            ),
        ),
    ]
