# Generated by Django 5.2.17 on 2026-09-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0041_libelles_et_voies_encaissement"),
    ]

    operations = [
        migrations.AddField(
            model_name="accmove",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves",
                to="accounting.accpaymentterm",
            ),
        ),
    ]
