# Generated by Django 5.2.17 on 2026-08-28 20:23

import apps.core.db.fields
import apps.core.db.uuid7
import django.db.models.deletion
import django_fsm
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("employee_id", models.UUIDField()),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("repayment_months", models.PositiveSmallIntegerField(default=1)),
                (
                    "remaining",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("requested", "Demandee"),
                            ("approved", "Approuvee"),
                            ("repaying", "En remboursement"),
                            ("settled", "Soldee"),
                            ("rejected", "Refusee"),
                        ],
                        default="requested",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_advance",
            },
        ),
        migrations.CreateModel(
            name="PayBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("controlled", "Controle"),
                            ("validated", "Valide"),
                            ("cancelled", "Annule"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_social",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_batch",
            },
        ),
        migrations.CreateModel(
            name="PayContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("employee_id", models.UUIDField()),
                ("date_start", models.DateField()),
                ("date_end", models.DateField(blank=True, null=True)),
                ("trial_end", models.DateField(blank=True, null=True)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("department_id", models.UUIDField(blank=True, null=True)),
                ("workshop_id", models.UUIDField(blank=True, null=True)),
                ("wage_base", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "wage_type",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("horaire", "Horaire"),
                            ("journalier", "Journalier"),
                            ("piece", "Aux pieces"),
                        ],
                        default="mensuel",
                        max_length=16,
                    ),
                ),
                ("work_calendar_id", models.UUIDField(blank=True, null=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("ended", "Termine"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("notice_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="payroll.paycontract",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_contract",
            },
        ),
        migrations.CreateModel(
            name="PayContractBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("prime_transport", "Prime de transport"),
                            ("prime_anciennete", "Prime d'anciennete"),
                            ("prime_rendement", "Prime de rendement"),
                            ("indemnite_logement", "Indemnite de logement"),
                            ("indemnite_repas", "Indemnite de repas"),
                            ("telephone", "Telephone"),
                            ("assurance_sante", "Assurance sante"),
                            ("avantage_nature", "Avantage en nature"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "computation",
                    models.CharField(
                        choices=[
                            ("fixe", "Fixe"),
                            ("pourcentage", "Pourcentage"),
                            ("formule", "Formule"),
                        ],
                        default="fixe",
                        max_length=16,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_subject_to_social", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("mensuelle", "Mensuelle"),
                            ("annuelle", "Annuelle"),
                            ("ponctuelle", "Ponctuelle"),
                        ],
                        default="mensuelle",
                        max_length=16,
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="payroll.paycontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_contract_benefit",
            },
        ),
        migrations.CreateModel(
            name="PayContractType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("essai", "Essai"),
                            ("stage", "Stage"),
                            ("apprentissage", "Apprentissage"),
                            ("journalier", "Journalier"),
                            ("saisonnier", "Saisonnier"),
                            ("prestation", "Prestation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("default_notice_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_duration_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_renewable", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_contract_type",
            },
        ),
        migrations.AddField(
            model_name="paycontract",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="payroll.paycontracttype",
            ),
        ),
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("en_calcul", "En calcul"),
                            ("verifiee", "Verifiee"),
                            ("validee", "Validee"),
                            ("payee", "Payee"),
                            ("cloturee", "Cloturee"),
                        ],
                        default="ouverte",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_period",
            },
        ),
        migrations.CreateModel(
            name="PayPayslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("employee_id", models.UUIDField()),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "worked_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "worked_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                ("absence_days", models.JSONField(blank=True, default=list)),
                ("overtime_hours", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("computed", "Calcule"),
                            ("to_approve", "A approuver"),
                            ("approved", "Approuve"),
                            ("paid", "Paye"),
                            ("cancelled", "Annule"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "irsa",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "social_employee",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "social_employer",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_to_pay",
                    apps.core.db.fields.EncryptedDecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("banque", "Virement bancaire"),
                            ("mobile_money", "Mobile money"),
                            ("especes", "Especes"),
                        ],
                        default="banque",
                        max_length=16,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("move_id", models.UUIDField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payslips",
                        to="payroll.paybatch",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="payroll.paycontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rectifies",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rectifications",
                        to="payroll.paypayslip",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="payroll.payperiod",
                    ),
                ),
            ],
            options={
                "db_table": "pay_payslip",
            },
        ),
        migrations.CreateModel(
            name="PayDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("irsa", "IRSA"),
                            ("cnaps", "CNaPS"),
                            ("ostie", "OSTIE"),
                            ("dts", "DTS"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[("draft", "Brouillon"), ("submitted", "Soumise")],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declarations",
                        to="payroll.payperiod",
                    ),
                ),
            ],
            options={
                "db_table": "pay_declaration",
            },
        ),
        migrations.AddField(
            model_name="paybatch",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="payroll.payperiod",
            ),
        ),
        migrations.CreateModel(
            name="PaySalaryRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=10)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("brut", "Brut"),
                            ("cotisation_salariale", "Cotisation salariale"),
                            ("cotisation_patronale", "Cotisation patronale"),
                            ("impot", "Impot"),
                            ("retenue", "Retenue"),
                            ("net_imposable", "Net imposable"),
                            ("net_a_payer", "Net a payer"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("toujours", "Toujours"),
                            ("python", "Expression"),
                            ("plage", "Plage"),
                        ],
                        default="toujours",
                        max_length=16,
                    ),
                ),
                ("condition", models.TextField(blank=True)),
                (
                    "amount_type",
                    models.CharField(
                        choices=[
                            ("fixe", "Fixe"),
                            ("pourcentage", "Pourcentage"),
                            ("python", "Expression"),
                        ],
                        default="fixe",
                        max_length=16,
                    ),
                ),
                ("amount", models.TextField(blank=True)),
                ("base_code", models.CharField(blank=True, max_length=32)),
                ("appears_on_payslip", models.BooleanField(default=True)),
                ("account_debit_id", models.UUIDField(blank=True, null=True)),
                ("account_credit_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_salary_rule",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="PayPayslipLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=10)),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("brut", "Brut"),
                            ("cotisation_salariale", "Cotisation salariale"),
                            ("cotisation_patronale", "Cotisation patronale"),
                            ("impot", "Impot"),
                            ("retenue", "Retenue"),
                            ("net_imposable", "Net imposable"),
                            ("net_a_payer", "Net a payer"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_employer_charge", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payroll.paypayslip",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payroll.paysalaryrule",
                    ),
                ),
            ],
            options={
                "db_table": "pay_payslip_line",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="PaySalaryStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                ("country", models.CharField(default="MG", max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="payroll.paysalarystructure",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_salary_structure",
            },
        ),
        migrations.AddField(
            model_name="paysalaryrule",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="payroll.paysalarystructure",
            ),
        ),
        migrations.AddField(
            model_name="paycontract",
            name="salary_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="payroll.paysalarystructure",
            ),
        ),
        migrations.AddConstraint(
            model_name="paycontracttype",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_pay_contract_type_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="payperiod",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_pay_period_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="paysalarystructure",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_pay_structure_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="paysalaryrule",
            constraint=models.UniqueConstraint(
                fields=("structure", "code"), name="uniq_pay_salary_rule_code"
            ),
        ),
    ]
