# Generated by Django 5.2.17 on 2026-09-01 06:17

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payadvance",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("requested", "Demandée"),
                    ("approved", "Approuvée"),
                    ("repaying", "En remboursement"),
                    ("settled", "Soldée"),
                    ("rejected", "Refusée"),
                ],
                default="requested",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paycontract",
            name="wage_type",
            field=models.CharField(
                choices=[
                    ("mensuel", "Mensuel"),
                    ("horaire", "Horaire"),
                    ("journalier", "Journalier"),
                    ("piece", "Aux pièces"),
                ],
                default="mensuel",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="paycontractbenefit",
            name="type",
            field=models.CharField(
                choices=[
                    ("prime_transport", "Prime de transport"),
                    ("prime_anciennete", "Prime d'ancienneté"),
                    ("prime_rendement", "Prime de rendement"),
                    ("indemnite_logement", "Indemnité de logement"),
                    ("indemnite_repas", "Indemnité de repas"),
                    ("telephone", "Téléphone"),
                    ("assurance_sante", "Assurance santé"),
                    ("avantage_nature", "Avantage en nature"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="paypayslip",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("banque", "Virement bancaire"),
                    ("mobile_money", "Mobile money"),
                    ("especes", "Espèces"),
                ],
                default="banque",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="paypayslipline",
            name="category",
            field=models.CharField(
                choices=[
                    ("base", "Base"),
                    ("brut", "Brut"),
                    ("cotisation_salariale", "Cotisation salariale"),
                    ("cotisation_patronale", "Cotisation patronale"),
                    ("impot", "Impôt"),
                    ("retenue", "Retenue"),
                    ("net_imposable", "Net imposable"),
                    ("net_a_payer", "Net a payer"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("ouverte", "Ouverte"),
                    ("en_calcul", "En calcul"),
                    ("verifiee", "Vérifiée"),
                    ("validee", "Validée"),
                    ("payee", "Payée"),
                    ("cloturee", "Clôturée"),
                ],
                default="ouverte",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paysalaryrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("base", "Base"),
                    ("brut", "Brut"),
                    ("cotisation_salariale", "Cotisation salariale"),
                    ("cotisation_patronale", "Cotisation patronale"),
                    ("impot", "Impôt"),
                    ("retenue", "Retenue"),
                    ("net_imposable", "Net imposable"),
                    ("net_a_payer", "Net a payer"),
                ],
                max_length=24,
            ),
        ),
    ]
