# Generated by Django 5.2.17 on 2026-09-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_alter_payadvance_state_alter_paycontract_wage_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypayslipline",
            name="regulatory_parameter_versions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
