# Generated by Django 5.2.17 on 2026-09-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_paypayslipline_regulatory_parameter_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="paybatch",
            name="anomaly_acknowledgments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
