# Generated by Django 5.2.17 on 2026-08-28 00:09

import apps.core.db.uuid7
import apps.purchase.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("purchase", "0002_pursubstitute_purrequisitionline_substitute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("partner_id", models.UUIDField()),
                ("date", models.DateField()),
                ("date_expected", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="MGA", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1, max_digits=18),
                ),
                ("payment_term_id", models.UUIDField(blank=True, null=True)),
                (
                    "incoterm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW — A l'usine"),
                            ("FOB", "FOB — Franco a bord"),
                            ("CIF", "CIF — Cout, assurance et fret"),
                            ("DAP", "DAP — Rendu au lieu de destination"),
                            ("DDP", "DDP — Rendu droits acquittes"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("import_chine", "Import Chine"),
                            ("import_autre", "Import autre"),
                            ("en_ligne", "En ligne"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("to_validate", "A valider"),
                            ("validated", "Validee"),
                            ("sent", "Envoyee"),
                            ("confirmed", "Confirmee"),
                            ("in_transit", "En transit"),
                            ("partially_received", "Recue partiellement"),
                            ("received", "Recue"),
                            ("invoiced", "Facturee"),
                            ("closed", "Cloturee"),
                            ("cancelled", "Annulee"),
                            ("in_dispute", "En litige"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "amount_untaxed_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_tax_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "amount_total_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("warehouse_id", models.UUIDField(blank=True, null=True)),
                ("analytic_account_id", models.UUIDField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                ("dispute_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="purchase.purrequisition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_order",
            },
        ),
        migrations.CreateModel(
            name="PurOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("variant_id", models.UUIDField()),
                ("supplier_sku", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(max_length=255)),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=1, max_digits=18),
                ),
                ("uom", models.CharField(blank=True, max_length=16)),
                (
                    "unit_price_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "subtotal_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_received",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qty_invoiced",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("date_expected", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase.purorder",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="purchase.pursubstitute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_order_line",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="PurRfq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("date", models.DateField()),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoye"),
                            ("closed", "Cloture"),
                            ("awarded", "Attribue"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "award_criteria",
                    models.JSONField(
                        default=apps.purchase.models._default_award_criteria
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_rfq",
            },
        ),
        migrations.AddField(
            model_name="purorder",
            name="rfq",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="purchase.purrfq",
            ),
        ),
        migrations.CreateModel(
            name="PurRfqLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("variant_id", models.UUIDField()),
                ("description", models.CharField(max_length=255)),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=1, max_digits=18),
                ),
                ("uom", models.CharField(blank=True, max_length=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase.purrfq",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_rfq_line",
            },
        ),
        migrations.CreateModel(
            name="PurRfqResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.UUIDField()),
                ("date_received", models.DateField()),
                (
                    "total_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("currency", models.CharField(default="MGA", max_length=3)),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                ("validity_date", models.DateField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="purchase.purrfq",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_rfq_response",
            },
        ),
        migrations.CreateModel(
            name="PurRfqResponseLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("variant_id", models.UUIDField()),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=1, max_digits=18),
                ),
                (
                    "unit_price_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase.purrfqresponse",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_rfq_response_line",
            },
        ),
        migrations.CreateModel(
            name="PurRfqSupplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.UUIDField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="purchase.purrfq",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_rfq_supplier",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rfq", "partner_id"),
                        name="uniq_pur_rfq_supplier_rfq_partner",
                    )
                ],
            },
        ),
    ]
