# Generated by Django 5.2.17 on 2026-08-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_purreceiptline_purreorderingrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="purorder",
            name="import_dossier_pending",
            field=models.BooleanField(default=False),
        ),
    ]
