# Generated by Django 5.2.17 on 2026-08-29 14:18

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_qltchecklisttemplate_qltinspection"),
        ("purchase", "0006_purcra_purcri"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrcPriceWatchTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("material_reference_id", models.UUIDField(blank=True, null=True)),
                ("variant_id", models.UUIDField(blank=True, null=True)),
                (
                    "platform_code",
                    models.CharField(
                        choices=[
                            ("alibaba", "Alibaba"),
                            ("1688", "1688.com"),
                            ("aliexpress", "AliExpress"),
                            ("europages", "Europages"),
                            ("kompass", "Kompass"),
                            ("autre", "Autre"),
                        ],
                        max_length=16,
                    ),
                ),
                ("search_query_or_url", models.TextField()),
                ("currency", models.CharField(default="MGA", max_length=8)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuelle"),
                            ("quarterly", "Trimestrielle"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prc_price_watch_target",
                "permissions": [
                    (
                        "run_price_watch_check",
                        "Peut declencher manuellement une verification de veille prix (PRC1-3)",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrcPriceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "observed_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("source_note", models.TextField(blank=True)),
                ("is_stub", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="purchase.prcpricewatchtarget",
                    ),
                ),
            ],
            options={
                "db_table": "prc_price_snapshot",
                "ordering": ["-observed_at"],
            },
        ),
    ]
