# Generated by Django 5.2.17 on 2026-09-05 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.db.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_tenant_whatsapp_cost_alert_threshold_pct_and_more"),
        ("purchase", "0007_prcpricewatchtarget_prcpricesnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurReorderingProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("variant_id", models.UUIDField()),
                ("warehouse_id", models.UUIDField(blank=True, null=True)),
                ("qty_proposed", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "available_stock",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("on_order_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approval_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reordering_proposals",
                        to="purchase.purrequisition",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="purchase.purreorderingrule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_reordering_proposal",
            },
        ),
    ]
