# Generated by Django 5.2.17 on 2026-09-04 00:08

import apps.core.db.uuid7
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0029_tenant_whatsapp_cost_alert_threshold_pct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=32)),
                ("chat_channel_id", models.CharField(blank=True, max_length=64)),
                (
                    "intent_state",
                    models.CharField(
                        choices=[
                            ("none", "Aucun"),
                            ("menu_sent", "Menu envoyé"),
                            ("awaiting_human", "En attente d'un humain"),
                            ("resolved", "Résolu"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("last_outbound_at", models.DateTimeField(blank=True, null=True)),
                ("consent_granted_at", models.DateTimeField(blank=True, null=True)),
                ("consent_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("consent_source", models.CharField(blank=True, max_length=100)),
                (
                    "consent_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wa_conversation",
                "ordering": ["-last_inbound_at", "-last_outbound_at"],
                "permissions": [
                    (
                        "run_message_retry",
                        "Peut relancer l'envoi des messages WhatsApp en échec (WA-7)",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "phone_number"),
                        name="uniq_wa_conversation_phone_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaMessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("utility", "Utilitaire"),
                            ("authentication", "Authentification"),
                        ],
                        max_length=16,
                    ),
                ),
                ("language", models.CharField(default="fr", max_length=8)),
                ("body_text", models.TextField()),
                ("variables", models.JSONField(blank=True, default=list)),
                (
                    "estimated_cost_ariary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_review", "En attente de validation"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wa_message_template",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "code"),
                        name="uniq_wa_message_template_code_per_tenant",
                    )
                ],
            },
        ),
    ]
