# Generated by Django 5.2.17 on 2026-09-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_rptschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="rptdefinition",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rptdefinition",
            name="owner_role",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
