# Generated by Django 5.2.17 on 2026-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "En cours"),
                    ("success", "Succès"),
                    ("failed", "Échec"),
                    ("partial", "Partiel"),
                ],
                default="running",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="autorunstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("success", "Succès"),
                    ("failed", "Échec"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
