# Generated by Django 5.2.17 on 2026-09-06 15:42

import apps.core.db.fields
import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0033_tenant_whatsapp_phone_number_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlwConnector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("fiscal", "Conformité fiscale"),
                            ("paiement", "Encaissement"),
                            ("banque", "Flux bancaires"),
                            ("bureautique", "Bureautique et stockage"),
                            ("commerce", "Commerce"),
                            ("messagerie", "Messagerie"),
                        ],
                        max_length=16,
                    ),
                ),
                ("supported_operations", models.JSONField(blank=True, default=list)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_connector",
                "ordering": ["family", "code"],
            },
        ),
        migrations.CreateModel(
            name="FlwCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cle_api", "Clé d'API"),
                            ("jeton_oauth", "Jeton OAuth"),
                            ("identifiant_mot_de_passe", "Identifiant et mot de passe"),
                            ("certificat", "Certificat"),
                            ("secret_webhook", "Secret de webhook"),
                        ],
                        max_length=32,
                    ),
                ),
                ("secret", apps.core.db.fields.EncryptedCharField(max_length=4096)),
                ("secret_hint", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="flows.flwconnector",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_credential",
                "ordering": ["connector", "label"],
            },
        ),
        migrations.CreateModel(
            name="FlwLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("endpoint_url", models.URLField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("active", "Active"),
                            ("suspendue", "Suspendue"),
                        ],
                        default="brouillon",
                        max_length=16,
                    ),
                ),
                ("suspended_reason", models.TextField(blank=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="flows.flwconnector",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links",
                        to="flows.flwcredential",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_link",
                "ordering": ["connector", "name"],
            },
        ),
        migrations.CreateModel(
            name="FlwExchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("sortant", "Sortant"), ("entrant", "Entrant")],
                        max_length=8,
                    ),
                ),
                ("operation", models.CharField(max_length=32)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepare", "Préparé"),
                            ("en_file", "En file"),
                            ("emis", "Émis"),
                            ("accepte", "Accepté"),
                            ("rejete", "Rejeté"),
                            ("attente_verdict", "En attente de verdict"),
                            ("a_reessayer", "À réessayer"),
                            ("en_echec", "En échec"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="prepare",
                        max_length=24,
                    ),
                ),
                ("document_type", models.CharField(blank=True, max_length=64)),
                ("document_id", models.UUIDField(blank=True, null=True)),
                (
                    "correlation_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("payload_fingerprint", models.CharField(blank=True, max_length=64)),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("result_code", models.CharField(blank=True, max_length=64)),
                ("result_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("partition_month", models.DateField(db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchanges",
                        to="flows.flwlink",
                    ),
                ),
            ],
            options={
                "db_table": "flw_exchange",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlwMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("document_type", models.CharField(max_length=64)),
                ("field_map", models.JSONField(blank=True, default=dict)),
                ("target_schema", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="flows.flwlink",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_mapping",
                "ordering": ["link", "document_type"],
            },
        ),
        migrations.CreateModel(
            name="FlwPayload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(default="application/json", max_length=64),
                ),
                ("body", models.TextField()),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("retain_until", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exchange",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payload",
                        to="flows.flwexchange",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_payload",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlwSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("operation", models.CharField(max_length=32)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("horaire", "Chaque heure"),
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hour", models.PositiveSmallIntegerField(default=2)),
                ("skip_public_holidays", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="flows.flwlink",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_schedule",
                "ordering": ["link", "operation"],
            },
        ),
        migrations.CreateModel(
            name="FlwTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("event_name", models.CharField(max_length=128)),
                ("operation", models.CharField(max_length=32)),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="flows.flwlink",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_trigger",
                "ordering": ["link", "event_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="flwconnector",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_flw_connector_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="flwlink",
            constraint=models.UniqueConstraint(
                fields=("tenant", "connector", "name"),
                name="uniq_flw_link_name_per_connector",
            ),
        ),
        migrations.AddIndex(
            model_name="flwexchange",
            index=models.Index(
                fields=["tenant", "state"], name="idx_flw_exchange_state"
            ),
        ),
        migrations.AddIndex(
            model_name="flwexchange",
            index=models.Index(
                fields=["tenant", "document_type", "document_id"],
                name="idx_flw_exchange_document",
            ),
        ),
        migrations.AddIndex(
            model_name="flwexchange",
            index=models.Index(
                fields=["partition_month", "link"], name="idx_flw_exch_part_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="flwexchange",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uniq_flw_exchange_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="flwmapping",
            constraint=models.UniqueConstraint(
                fields=("tenant", "link", "document_type"),
                name="uniq_flw_mapping_per_link_and_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="flwtrigger",
            constraint=models.UniqueConstraint(
                fields=("tenant", "link", "event_name", "operation"),
                name="uniq_flw_trigger_per_event_and_operation",
            ),
        ),
    ]
