# Generated by Django 5.2.17 on 2026-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flwexchange",
            name="cost_ariary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
