# Generated by Django 5.2.17 on 2026-09-06 18:21

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_tenant_whatsapp_phone_number_id_and_more"),
        ("flows", "0002_flwexchange_cost_ariary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flwconnector",
            name="max_in_flight",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="alert_recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="breaker_cooldown_seconds",
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="breaker_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="breaker_state",
            field=models.CharField(
                choices=[
                    ("ferme", "Fermé"),
                    ("ouvert", "Ouvert"),
                    ("demi_ouvert", "Demi-ouvert"),
                ],
                default="ferme",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="breaker_threshold",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="consecutive_failures",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="on_attempts_exhausted",
            field=models.CharField(
                choices=[
                    ("mise_en_attente", "Mise en attente"),
                    ("abandon_trace", "Abandon tracé"),
                ],
                default="mise_en_attente",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="retry_backoff_seconds",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.CreateModel(
            name="FlwIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("identifiants", "Identifiants à renouveler"),
                            (
                                "donnee_invalide",
                                "Donnée manquante ou invalide dans la pièce",
                            ),
                            ("refus_tiers", "Refus motivé par le tiers"),
                            ("tiers_indisponible", "Tiers indisponible"),
                            ("plafond_atteint", "Plafond atteint"),
                            ("anomalie_editeur", "Anomalie à signaler à l'éditeur"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("pris_en_charge", "Pris en charge"),
                            ("resolu", "Résolu"),
                        ],
                        default="ouvert",
                        max_length=16,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("last_result_code", models.CharField(blank=True, max_length=64)),
                ("last_result_message", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="flows.flwlink",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flw_incident",
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "state"], name="idx_flw_incident_state"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state__in", ("ouvert", "pris_en_charge"))),
                        fields=("tenant", "link", "family"),
                        name="uniq_flw_incident_vivant_par_liaison_famille",
                    )
                ],
            },
        ),
    ]
