"""S6 — le vocabulaire des operations devient un jeu ferme (cahier §4.1).

Aucun SQL : `choices` et `validators` sont des contraintes Django, pas des
contraintes PostgreSQL. La migration existe quand meme parce que l'etat des
modeles doit refleter les champs reels — sans elle,
`makemigrations --check` echouerait a chaque passe de verification, et le
jour ou une VRAIE migration serait oubliee, cet echec permanent l'aurait
deja rendu invisible.

**Pourquoi pas une contrainte de base.** Une `CheckConstraint` sur les huit
codes figerait le jeu ferme dans le schema : ajouter une operation
demanderait alors une migration de donnees sur trois tables, et le cahier
tient les huit pour limitatives DANS SA VERSION ACTUELLE, pas pour
l'eternite. La validation vit donc la ou le depot la met partout ailleurs
(FLX-6, les six transformations, les six familles) : dans le service et
dans `save()`, avec sa garde d'architecture.
"""


# Generated by Django 5.2.17 on 2026-09-07 16:04

import apps.flows.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0004_flwexchange_cost_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flwconnector",
            name="supported_operations",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.flows.operations.validate_supported_operations],
            ),
        ),
        migrations.AlterField(
            model_name="flwexchange",
            name="operation",
            field=models.CharField(
                choices=[
                    ("OP1", "OP1 — Pousser un document"),
                    ("OP2", "OP2 — Publier un jeu de données"),
                    ("OP3", "OP3 — Déposer un fichier"),
                    ("OP4", "OP4 — Soumettre pour validation"),
                    ("OP5", "OP5 — Initier un mouvement d'argent"),
                    ("OP6", "OP6 — Ingérer un lot"),
                    ("OP7", "OP7 — Recevoir un événement"),
                    ("OP8", "OP8 — Interroger un référentiel"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="flwschedule",
            name="operation",
            field=models.CharField(
                choices=[
                    ("OP1", "OP1 — Pousser un document"),
                    ("OP2", "OP2 — Publier un jeu de données"),
                    ("OP3", "OP3 — Déposer un fichier"),
                    ("OP4", "OP4 — Soumettre pour validation"),
                    ("OP5", "OP5 — Initier un mouvement d'argent"),
                    ("OP6", "OP6 — Ingérer un lot"),
                    ("OP7", "OP7 — Recevoir un événement"),
                    ("OP8", "OP8 — Interroger un référentiel"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="flwtrigger",
            name="operation",
            field=models.CharField(
                choices=[
                    ("OP1", "OP1 — Pousser un document"),
                    ("OP2", "OP2 — Publier un jeu de données"),
                    ("OP3", "OP3 — Déposer un fichier"),
                    ("OP4", "OP4 — Soumettre pour validation"),
                    ("OP5", "OP5 — Initier un mouvement d'argent"),
                    ("OP6", "OP6 — Ingérer un lot"),
                    ("OP7", "OP7 — Recevoir un événement"),
                    ("OP8", "OP8 — Interroger un référentiel"),
                ],
                max_length=32,
            ),
        ),
    ]
