"""S6, FLX-5 — l'index que la purge quotidienne exige.

`retain_until` etait declare depuis S1 sans index, et sans purge. La purge
arrive au meme sprint que son index, et c'est deliberé : une purge livree
sans index balaye chaque nuit la table la plus volumineuse du hub, et le
jour ou elle devient lente est celui ou elle cesse d'etre executee.

Trois colonnes parce que la purge a deux chemins : la date explicite, et
son absence — auquel cas la politique par defaut se prononce sur
`created_at`. Deux index separes auraient coute deux ecritures a chaque
insertion pour couvrir ce qu'un seul couvre.
"""


# Generated by Django 5.2.17 on 2026-09-07 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_remove_country_defaults_holidays"),
        ("flows", "0005_close_the_operations_vocabulary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flwpayload",
            index=models.Index(
                fields=["tenant", "retain_until", "created_at"],
                name="idx_flw_payload_retention",
            ),
        ),
    ]
