# Generated by Django 5.2.17 on 2026-09-09 22:59

import apps.flows.pricing_regimes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0009_flwlink_readable_without_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="flwconnector",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="flwconnector",
            name="pricing_regime",
            field=models.CharField(
                blank=True,
                choices=[
                    ("socle_inclus", "Socle inclus"),
                    ("abonnement_module", "Abonnement de module"),
                    ("a_l_usage", "À l'usage"),
                ],
                max_length=20,
                validators=[apps.flows.pricing_regimes.validate_pricing_regime],
            ),
        ),
        migrations.AddField(
            model_name="flwconnector",
            name="retention_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="cost_alert_threshold_pct",
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="cost_alerted_for_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="monthly_cost_cap_ariary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
