# Generated by Django 5.2.17 on 2026-09-09 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0011_t9_consent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flwlink",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revoked_flow_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flwlink",
            name="revoked_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="flwlink",
            name="state",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("active", "Active"),
                    ("suspendue", "Suspendue"),
                    ("revoquee", "Révoquée"),
                ],
                default="brouillon",
                max_length=16,
            ),
        ),
    ]
