# Generated by Django 5.2.17 on 2026-09-01 06:17

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_prjguestaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prjcustomfielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Texte"),
                    ("number", "Nombre"),
                    ("date", "Date"),
                    ("boolean", "Booléen"),
                    ("choice", "Choix"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="prjinvoicingrecord",
            name="mode",
            field=models.CharField(
                choices=[
                    ("milestone", "Jalon"),
                    ("percentage", "Pourcentage d'avancement"),
                    ("time_and_material", "Régie temps & matériel"),
                    ("fixed", "Forfait"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prjtask",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("todo", "A faire"),
                    ("in_progress", "En cours"),
                    ("blocked", "Bloquée"),
                    ("done", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                default="todo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="prjtaskdependency",
            name="dependency_type",
            field=models.CharField(
                choices=[
                    ("finish_to_start", "Fin -> Début"),
                    ("start_to_start", "Début -> Début"),
                    ("finish_to_finish", "Fin -> Fin"),
                    ("start_to_finish", "Début -> Fin"),
                ],
                default="finish_to_start",
                max_length=20,
            ),
        ),
    ]
