# Generated by Django 5.2.17 on 2026-09-01 06:17

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0004_hlpcsatresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hlpescalationrule",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("time_since_created", "Temps depuis création"),
                    ("time_since_last_activity", "Temps depuis dernière activité"),
                    ("sla_breach", "Brèche de SLA"),
                    ("min_priority", "Priorité minimale"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="hlpslabreach",
            name="breach_type",
            field=models.CharField(
                choices=[
                    ("first_response", "Première réponse"),
                    ("resolution", "Résolution"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="hlpticket",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "Nouveau"),
                    ("in_progress", "En cours"),
                    ("pending", "En attente"),
                    ("resolved", "Résolu"),
                    ("closed", "Clôturé"),
                    ("escalated", "Escalade"),
                    ("cancelled", "Annule"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hlptickettypecatalog",
            name="sector_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("textile", "Textile"),
                    ("cuir", "Cuir et maroquinerie"),
                    ("agroalimentaire", "Agroalimentaire"),
                    ("import_export", "Import-export généraliste"),
                    ("artisanat", "Artisanat"),
                ],
                max_length=32,
            ),
        ),
    ]
