# Generated by Django 5.2.17 on 2026-08-28 12:54

import apps.core.db.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogDriver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("license_number", models.CharField(blank=True, max_length=64)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("consent_geolocation", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "log_driver",
            },
        ),
        migrations.CreateModel(
            name="LogVehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("plate_number", models.CharField(max_length=32)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("truck", "Camion"),
                            ("van", "Camionnette"),
                            ("motorcycle", "Moto"),
                            ("other", "Autre"),
                        ],
                        default="truck",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "En service"),
                            ("maintenance", "En maintenance"),
                            ("retired", "Retire"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "capacity_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "odometer_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "log_vehicle",
            },
        ),
        migrations.CreateModel(
            name="LogVehicleCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("fuel", "Carburant"),
                            ("maintenance", "Entretien"),
                            ("insurance", "Assurance"),
                            ("toll", "Peage"),
                            ("other", "Autre"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount_mga", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "odometer_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="logistics.logvehicle",
                    ),
                ),
            ],
            options={
                "db_table": "log_vehicle_cost",
            },
        ),
        migrations.CreateModel(
            name="LogVehicleDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("insurance", "Assurance"),
                            ("registration", "Carte grise"),
                            ("technical_inspection", "Visite technique"),
                            ("permit", "Autorisation/permis"),
                            ("other", "Autre"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("alert_days_before", models.PositiveSmallIntegerField(default=30)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="logistics.logvehicle",
                    ),
                ),
            ],
            options={
                "db_table": "log_vehicle_document",
            },
        ),
        migrations.AddConstraint(
            model_name="logvehicle",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plate_number"), name="uniq_log_vehicle_plate_number"
            ),
        ),
        migrations.AddIndex(
            model_name="logvehiclecost",
            index=models.Index(
                fields=["tenant", "vehicle", "date"],
                name="log_vehicle_tenant__53884f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="logvehicledocument",
            index=models.Index(
                fields=["tenant", "expiry_date"], name="log_vehicle_tenant__ddece6_idx"
            ),
        ),
    ]
