# Generated by Django 5.2.17 on 2026-08-28 13:42

import apps.core.db.uuid7
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tenant_vat_opted_in"),
        ("logistics", "0003_logpackagingplan_logpackagingtype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogShipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                (
                    "incoterm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW — A l'usine"),
                            ("FOB", "FOB — Franco a bord"),
                            ("CIF", "CIF — Cout, assurance et fret"),
                            ("DAP", "DAP — Rendu au lieu de destination"),
                            ("DDP", "DDP — Rendu droits acquittes"),
                        ],
                        max_length=8,
                    ),
                ),
                ("purchase_order_ids", models.JSONField(blank=True, default=list)),
                ("sales_order_ids", models.JSONField(blank=True, default=list)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "freight_cost_mga",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "freight_billed_to_customer_mga",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("planned", "Prevue"),
                            ("booked", "Reservee"),
                            ("picked_up", "Enlevee"),
                            ("in_transit", "En transit"),
                            ("arrived_at_port", "Arrivee au port"),
                            ("customs_clearance", "En dedouanement"),
                            ("customs_cleared", "Dedouanee"),
                            ("delivered", "Livree"),
                            ("closed", "Cloturee"),
                            ("blocked", "Bloquee"),
                        ],
                        default="planned",
                        max_length=50,
                    ),
                ),
                ("block_reason", models.TextField(blank=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="logistics.logserviceprovider",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "log_shipment",
            },
        ),
        migrations.CreateModel(
            name="LogShipmentLeg",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("road", "Route"),
                            ("sea", "Mer"),
                            ("air", "Air"),
                            ("rail", "Rail"),
                        ],
                        default="road",
                        max_length=8,
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="logistics.logserviceprovider",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="logistics.logshipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "log_shipment_leg",
                "ordering": ["sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shipment", "sequence"),
                        name="uniq_log_shipment_leg_sequence",
                    )
                ],
            },
        ),
    ]
