# Generated by Django 5.2.17 on 2026-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_logcustomsfile_loghscode_logcustomsline"),
    ]

    operations = [
        migrations.AddField(
            model_name="logserviceprovider",
            name="webhook_secret",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
