# Generated by Django 5.2.17 on 2026-09-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0006_logserviceprovider_webhook_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="logserviceprovider",
            name="partner_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
