# Generated by Django 5.2.17 on 2026-09-11 19:04

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0009_logserviceprovider_readable_without_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logcustomsfile",
            name="state",
            field=models.CharField(
                choices=[
                    ("open", "Ouvert"),
                    ("cleared", "Dédouané"),
                    ("closed", "Clôturé"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="logshipment",
            name="incoterm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW — À l'usine"),
                    ("FOB", "FOB — Franco a bord"),
                    ("CIF", "CIF — Coût, assurance et fret"),
                    ("DAP", "DAP — Rendu au lieu de destination"),
                    ("DDP", "DDP — Rendu droits acquittes"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="logshipment",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("planned", "Prévue"),
                    ("booked", "Réservée"),
                    ("picked_up", "Enlevée"),
                    ("in_transit", "En transit"),
                    ("arrived_at_port", "Arrivée au port"),
                    ("customs_clearance", "En dédouanement"),
                    ("customs_cleared", "Dédouanée"),
                    ("delivered", "Livrée"),
                    ("closed", "Clôturée"),
                    ("blocked", "Bloquée"),
                ],
                default="planned",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="logtrip",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planifié"),
                    ("in_progress", "En cours"),
                    ("completed", "Terminé"),
                    ("cancelled", "Annulé"),
                ],
                default="planned",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="logtripstop",
            name="status",
            field=models.CharField(
                choices=[("pending", "En attente"), ("completed", "Terminé")],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="logtripstop",
            name="type",
            field=models.CharField(
                choices=[
                    ("pickup", "Enlèvement"),
                    ("dropoff", "Livraison"),
                    ("other", "Autre"),
                ],
                default="dropoff",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="logvehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "En service"),
                    ("maintenance", "En maintenance"),
                    ("retired", "Retiré"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="logvehiclecost",
            name="cost_type",
            field=models.CharField(
                choices=[
                    ("fuel", "Carburant"),
                    ("maintenance", "Entretien"),
                    ("insurance", "Assurance"),
                    ("toll", "Péage"),
                    ("other", "Autre"),
                ],
                max_length=16,
            ),
        ),
    ]
